import { EquipmentItem } from '../types';

export const getDefaultFleet = (projectId: string = 'PRJ-OIL-2026'): EquipmentItem[] => [
  // ==========================================
  // 1. CRANES (6 Heavy Lifting Units)
  // ==========================================
  {
    id: 'EQ-CRANE-01',
    projectId,
    name: 'Tadano GR-500XL (50T Rough Terrain Crane)',
    category: 'CRANE',
    categoryName: 'Cranes',
    tag: 'Heavy Lifting · Spool Rigging',
    operator: 'Biren Chetia (Certified Heavy Operator)',
    status: 'ACTIVE',
    location: 'Line 24 Trench Corridor (Chainage 14+350)',
    operatingHours: '1,420 hrs',
    hoursToday: '6.4 hrs',
    fuelLevel: 78,
    engineTemp: '88°C (Normal)',
    batteryVoltage: '24.4 V',
    vibrationLevel: '0.8 mm/s (Optimal)',
    maintenanceDue: 'In 180 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3514, lng: 95.3128 },
      rpm: 1650,
      fuelRateLph: 14.2,
      hydraulicPressurePsi: 3100,
      oilPressurePsi: 65,
      engineLoadPct: 62,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '2 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-CRANE-02',
    projectId,
    name: 'Liebherr LTM 11200-9.1 (1200T Mobile Crane)',
    category: 'CRANE',
    categoryName: 'Cranes',
    tag: 'Super Heavy Erection · Terminal Pre-assembly',
    operator: 'Rajeshwar Sonowal (Master Rigger)',
    status: 'ACTIVE',
    location: 'Terminal Compressor Deck Zone A',
    operatingHours: '2,840 hrs',
    hoursToday: '5.1 hrs',
    fuelLevel: 84,
    engineTemp: '85°C (Normal)',
    batteryVoltage: '24.6 V',
    vibrationLevel: '0.6 mm/s (Optimal)',
    maintenanceDue: 'In 260 hrs',
    associatedAct: 'ACT-3088',
    telemetry: {
      gps: { lat: 27.3540, lng: 95.3180 },
      rpm: 1400,
      fuelRateLph: 26.5,
      hydraulicPressurePsi: 3450,
      oilPressurePsi: 70,
      engineLoadPct: 71,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '5 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-CRANE-03',
    projectId,
    name: 'Kobelco CKE2500-2 (250T Crawler Crane)',
    category: 'CRANE',
    categoryName: 'Cranes',
    tag: 'Viaduct Pier Foundation · Sheet Piling',
    operator: 'Manoranjan Das',
    status: 'ACTIVE',
    location: 'Pier 24 River Crossing Approach',
    operatingHours: '3,110 hrs',
    hoursToday: '7.2 hrs',
    fuelLevel: 69,
    engineTemp: '89°C (Normal)',
    batteryVoltage: '24.2 V',
    vibrationLevel: '0.9 mm/s (Optimal)',
    maintenanceDue: 'In 90 hrs',
    associatedAct: 'CIV-L5-019',
    telemetry: {
      gps: { lat: 27.3562, lng: 95.3210 },
      rpm: 1800,
      fuelRateLph: 21.0,
      hydraulicPressurePsi: 3200,
      oilPressurePsi: 68,
      engineLoadPct: 68,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '1 min ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-CRANE-04',
    projectId,
    name: 'Sany SCC800C (80T Lattice Boom Crawler Crane)',
    category: 'CRANE',
    categoryName: 'Cranes',
    tag: 'Pipe Stringing & Lower-in Operations',
    operator: 'Probin Saikia',
    status: 'ACTIVE',
    location: 'Chainage 16+100 Corridor Alignment',
    operatingHours: '1,760 hrs',
    hoursToday: '6.8 hrs',
    fuelLevel: 58,
    engineTemp: '91°C (Normal)',
    batteryVoltage: '24.1 V',
    vibrationLevel: '1.1 mm/s (Acceptable)',
    maintenanceDue: 'In 140 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3590, lng: 95.3255 },
      rpm: 1720,
      fuelRateLph: 16.8,
      hydraulicPressurePsi: 2980,
      oilPressurePsi: 62,
      engineLoadPct: 59,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '4 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-CRANE-05',
    projectId,
    name: 'Demag AC 250-5 (250T All-Terrain Mobile Crane)',
    category: 'CRANE',
    categoryName: 'Cranes',
    tag: 'Manifold Skids Heavy Placement',
    operator: 'Hemanta Borah',
    status: 'STANDBY',
    location: 'Central Terminal Staging Yard',
    operatingHours: '980 hrs',
    hoursToday: '1.2 hrs',
    fuelLevel: 91,
    engineTemp: '76°C (Normal)',
    batteryVoltage: '24.8 V',
    vibrationLevel: '0.4 mm/s (Optimal)',
    maintenanceDue: 'In 340 hrs',
    associatedAct: 'ACT-3088',
    telemetry: {
      gps: { lat: 27.3535, lng: 95.3165 },
      rpm: 850,
      fuelRateLph: 6.5,
      hydraulicPressurePsi: 1800,
      oilPressurePsi: 55,
      engineLoadPct: 22,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '12 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-CRANE-06',
    projectId,
    name: 'Zoomlion ZCC550H (55T Crawler Crane)',
    category: 'CRANE',
    categoryName: 'Cranes',
    tag: 'Pipeline Trench Tie-in Rigging',
    operator: 'Utpal Deka',
    status: 'ACTIVE',
    location: 'Block Valve Station 02 (Chainage 18+200)',
    operatingHours: '2,240 hrs',
    hoursToday: '5.6 hrs',
    fuelLevel: 72,
    engineTemp: '87°C (Normal)',
    batteryVoltage: '24.3 V',
    vibrationLevel: '0.7 mm/s (Optimal)',
    maintenanceDue: 'In 110 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3620, lng: 95.3310 },
      rpm: 1600,
      fuelRateLph: 15.0,
      hydraulicPressurePsi: 3050,
      oilPressurePsi: 64,
      engineLoadPct: 55,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '3 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },

  // ==========================================
  // 2. EXCAVATORS (6 Earthmoving Units)
  // ==========================================
  {
    id: 'EQ-EXCAV-01',
    projectId,
    name: 'Komatsu PC210-10M0 (21T Hydraulic Excavator)',
    category: 'EXCAVATOR',
    categoryName: 'Excavators',
    tag: 'Trenching & Shoring Removal',
    operator: 'M. Barman',
    status: 'ACTIVE',
    location: 'Chainage 15+000 Substation Approach',
    operatingHours: '1,680 hrs',
    hoursToday: '7.0 hrs',
    fuelLevel: 62,
    engineTemp: '86°C (Normal)',
    batteryVoltage: '24.2 V',
    vibrationLevel: '1.2 mm/s (Optimal)',
    maintenanceDue: 'In 120 hrs',
    associatedAct: 'CIV-L5-019',
    telemetry: {
      gps: { lat: 27.3528, lng: 95.3142 },
      rpm: 1950,
      fuelRateLph: 17.5,
      hydraulicPressurePsi: 4200,
      oilPressurePsi: 58,
      engineLoadPct: 74,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '1 min ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-EXCAV-02',
    projectId,
    name: 'CAT 336D2 L (36T Hydraulic Heavy Excavator)',
    category: 'EXCAVATOR',
    categoryName: 'Excavators',
    tag: 'Deep Trench Bedding & Rock Excavation',
    operator: 'Diganta Kalita',
    status: 'ACTIVE',
    location: 'Digboi Hill Cut Corridor Section 3',
    operatingHours: '3,420 hrs',
    hoursToday: '7.8 hrs',
    fuelLevel: 54,
    engineTemp: '90°C (Normal)',
    batteryVoltage: '24.0 V',
    vibrationLevel: '1.5 mm/s (Acceptable)',
    maintenanceDue: 'In 80 hrs',
    associatedAct: 'CIV-L5-019',
    telemetry: {
      gps: { lat: 27.3580, lng: 95.3240 },
      rpm: 1900,
      fuelRateLph: 24.8,
      hydraulicPressurePsi: 4600,
      oilPressurePsi: 60,
      engineLoadPct: 82,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '2 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-EXCAV-03',
    projectId,
    name: 'Hitachi ZX200-5G (20T Tracked Excavator)',
    category: 'EXCAVATOR',
    categoryName: 'Excavators',
    tag: 'Pipe Corridor Fine Grading & Spoil Dressing',
    operator: 'Noren Gogoi',
    status: 'ACTIVE',
    location: 'Chainage 14+800 Laydown Area',
    operatingHours: '2,190 hrs',
    hoursToday: '6.1 hrs',
    fuelLevel: 76,
    engineTemp: '84°C (Normal)',
    batteryVoltage: '24.4 V',
    vibrationLevel: '0.9 mm/s (Optimal)',
    maintenanceDue: 'In 210 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3522, lng: 95.3135 },
      rpm: 1750,
      fuelRateLph: 15.8,
      hydraulicPressurePsi: 3900,
      oilPressurePsi: 56,
      engineLoadPct: 65,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '4 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-EXCAV-04',
    projectId,
    name: 'Volvo EC480D (48T Heavy Crawler Excavator)',
    category: 'EXCAVATOR',
    categoryName: 'Excavators',
    tag: 'Mass Earthwork & Riverbed Dredging',
    operator: 'Bikash Mahanta',
    status: 'ACTIVE',
    location: 'Burhi Dihing River Crossing Span',
    operatingHours: '4,120 hrs',
    hoursToday: '8.0 hrs',
    fuelLevel: 48,
    engineTemp: '92°C (Normal)',
    batteryVoltage: '23.9 V',
    vibrationLevel: '1.4 mm/s (Acceptable)',
    maintenanceDue: 'In 60 hrs',
    associatedAct: 'CIV-L5-019',
    telemetry: {
      gps: { lat: 27.3650, lng: 95.3350 },
      rpm: 1850,
      fuelRateLph: 32.0,
      hydraulicPressurePsi: 4900,
      oilPressurePsi: 64,
      engineLoadPct: 86,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '3 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-EXCAV-05',
    projectId,
    name: 'Hyundai R215-9 Smart (21T Hydraulic Excavator)',
    category: 'EXCAVATOR',
    categoryName: 'Excavators',
    tag: 'Padding & Trench Backfilling Gang',
    operator: 'Amarjyoti Nath',
    status: 'STANDBY',
    location: 'Chainage 13+900 Reinstatement Zone',
    operatingHours: '1,250 hrs',
    hoursToday: '2.0 hrs',
    fuelLevel: 88,
    engineTemp: '78°C (Normal)',
    batteryVoltage: '24.5 V',
    vibrationLevel: '0.5 mm/s (Optimal)',
    maintenanceDue: 'In 290 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3490, lng: 95.3090 },
      rpm: 900,
      fuelRateLph: 7.2,
      hydraulicPressurePsi: 2100,
      oilPressurePsi: 52,
      engineLoadPct: 28,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '15 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-EXCAV-06',
    projectId,
    name: 'Kobelco SK380HD (38T Heavy Duty Excavator)',
    category: 'EXCAVATOR',
    categoryName: 'Excavators',
    tag: 'Hard Rock Breaker & Sub-base Fracturing',
    operator: 'Tridib Hazarika',
    status: 'ACTIVE',
    location: 'Quarry Spur Road Cut (Pier 26)',
    operatingHours: '2,970 hrs',
    hoursToday: '6.5 hrs',
    fuelLevel: 52,
    engineTemp: '91°C (Normal)',
    batteryVoltage: '24.1 V',
    vibrationLevel: '1.8 mm/s (Moderate)',
    maintenanceDue: 'In 130 hrs',
    associatedAct: 'CIV-L5-019',
    telemetry: {
      gps: { lat: 27.3570, lng: 95.3225 },
      rpm: 1980,
      fuelRateLph: 27.4,
      hydraulicPressurePsi: 4750,
      oilPressurePsi: 62,
      engineLoadPct: 84,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '2 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },

  // ==========================================
  // 3. WELDING RIGS (6 Precision Welding Units)
  // ==========================================
  {
    id: 'EQ-WELD-01',
    projectId,
    name: 'Lincoln Electric Dual Vantage 500 Diesel Gen-Rig',
    category: 'WELDING_RIG',
    categoryName: 'Welding Rigs',
    tag: 'Orbital & Downhill SMAW/TIG',
    operator: 'Tapan Das Gang (Lead 6G Welder)',
    status: 'ACTIVE',
    location: 'Line 24 Pipe Stringing Alignment (Joint #W24-06)',
    operatingHours: '2,150 hrs',
    hoursToday: '8.2 hrs',
    fuelLevel: 65,
    engineTemp: '92°C (Normal)',
    batteryVoltage: '12.8 V',
    vibrationLevel: '0.7 mm/s (Optimal)',
    maintenanceDue: 'Filter swap in 24 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3516, lng: 95.3130 },
      rpm: 1800,
      fuelRateLph: 7.5,
      arcTimeTodayHours: 5.4,
      amperageAvg: 240,
      voltageAvg: 28,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '1 min ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-WELD-02',
    projectId,
    name: 'Miller Big Blue 800 Duo Air Pak Mobile Rig',
    category: 'WELDING_RIG',
    categoryName: 'Welding Rigs',
    tag: 'Dual Operator Semi-Automatic FCAW',
    operator: 'Sunil Karmakar (Fitter-Welder Gang)',
    status: 'ACTIVE',
    location: 'Chainage 14+500 Tie-in Trench',
    operatingHours: '1,890 hrs',
    hoursToday: '7.5 hrs',
    fuelLevel: 58,
    engineTemp: '89°C (Normal)',
    batteryVoltage: '12.7 V',
    vibrationLevel: '0.8 mm/s (Optimal)',
    maintenanceDue: 'In 160 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3525, lng: 95.3140 },
      rpm: 1800,
      fuelRateLph: 8.8,
      arcTimeTodayHours: 4.9,
      amperageAvg: 280,
      voltageAvg: 31,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '3 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-WELD-03',
    projectId,
    name: 'Fronius TransPuls Synergic 5000 Orbital Rig',
    category: 'WELDING_RIG',
    categoryName: 'Welding Rigs',
    tag: 'Automatic Orbital High-Speed Pipeline Welding',
    operator: 'Joydeb Roy (Orbital Technician)',
    status: 'ACTIVE',
    location: 'Terminal Station Hydrotest Header',
    operatingHours: '1,340 hrs',
    hoursToday: '6.0 hrs',
    fuelLevel: 79,
    engineTemp: '84°C (Normal)',
    batteryVoltage: '13.1 V',
    vibrationLevel: '0.3 mm/s (Optimal)',
    maintenanceDue: 'In 220 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3542, lng: 95.3175 },
      rpm: 1500,
      fuelRateLph: 5.2,
      arcTimeTodayHours: 4.2,
      amperageAvg: 210,
      voltageAvg: 24,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '5 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-WELD-04',
    projectId,
    name: 'ESAB Renegade ET 300iP Pipeline Field Unit',
    category: 'WELDING_RIG',
    categoryName: 'Welding Rigs',
    tag: 'Root Pass High-Frequency TIG & Hot Pass',
    operator: 'Pradip Chutia',
    status: 'ACTIVE',
    location: 'River Crossing Micro-tunnel Shaft',
    operatingHours: '950 hrs',
    hoursToday: '6.9 hrs',
    fuelLevel: 71,
    engineTemp: '86°C (Normal)',
    batteryVoltage: '12.9 V',
    vibrationLevel: '0.5 mm/s (Optimal)',
    maintenanceDue: 'In 270 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3645, lng: 95.3340 },
      rpm: 1700,
      fuelRateLph: 6.1,
      arcTimeTodayHours: 5.1,
      amperageAvg: 195,
      voltageAvg: 22,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '2 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-WELD-05',
    projectId,
    name: 'Lincoln Fleet-Air 400 Track Welding Tractor',
    category: 'WELDING_RIG',
    categoryName: 'Welding Rigs',
    tag: 'Crawler Cross-Country Pipeline Welding Spread',
    operator: 'Hiren Tamuli',
    status: 'STANDBY',
    location: 'Mobilization Yard B',
    operatingHours: '3,200 hrs',
    hoursToday: '0.5 hrs',
    fuelLevel: 94,
    engineTemp: '72°C (Normal)',
    batteryVoltage: '13.2 V',
    vibrationLevel: '0.4 mm/s (Optimal)',
    maintenanceDue: 'In 310 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3505, lng: 95.3110 },
      rpm: 800,
      fuelRateLph: 3.0,
      arcTimeTodayHours: 0.0,
      amperageAvg: 0,
      voltageAvg: 0,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '20 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-WELD-06',
    projectId,
    name: 'Kemppi MasterTig 4004 HD Field Rig',
    category: 'WELDING_RIG',
    categoryName: 'Welding Rigs',
    tag: 'High-Alloy Manifold & Valve Spool Welding',
    operator: 'Ananta Phukan',
    status: 'ACTIVE',
    location: 'Terminal Pig Trap & Valve Skids',
    operatingHours: '1,620 hrs',
    hoursToday: '5.8 hrs',
    fuelLevel: 68,
    engineTemp: '88°C (Normal)',
    batteryVoltage: '12.8 V',
    vibrationLevel: '0.6 mm/s (Optimal)',
    maintenanceDue: 'In 150 hrs',
    associatedAct: 'ACT-3088',
    telemetry: {
      gps: { lat: 27.3550, lng: 95.3190 },
      rpm: 1650,
      fuelRateLph: 5.9,
      arcTimeTodayHours: 4.5,
      amperageAvg: 230,
      voltageAvg: 26,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '4 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },

  // ==========================================
  // 4. DG SETS (6 Diesel Power Generation Units)
  // ==========================================
  {
    id: 'EQ-DGSET-01',
    projectId,
    name: 'Cummins Powerica 250 kVA Silent Acoustic DG Set',
    category: 'DG_SET',
    categoryName: 'DG sets',
    tag: 'Pipeline Field Camp & Office Prime Power',
    operator: 'Bipul Bora (Station Electrical Operator)',
    status: 'ACTIVE',
    location: 'Site HQ Camp (Chainage 14+000)',
    operatingHours: '4,850 hrs',
    hoursToday: '14.2 hrs',
    fuelLevel: 82,
    engineTemp: '87°C (Normal)',
    batteryVoltage: '24.6 V',
    vibrationLevel: '1.0 mm/s (Optimal)',
    maintenanceDue: 'In 150 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3500, lng: 95.3105 },
      rpm: 1500,
      fuelRateLph: 28.4,
      outputFrequency: 50.1,
      lineVoltage: 415,
      powerFactor: 0.88,
      engineLoadPct: 68,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '1 min ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-DGSET-02',
    projectId,
    name: 'Kirloskar 380 kVA Heavy Duty Diesel Generator',
    category: 'DG_SET',
    categoryName: 'DG sets',
    tag: 'Batching Plant & Concrete Chiller Power',
    operator: 'D. Kalita',
    status: 'ACTIVE',
    location: 'Central Concrete Batching Plant Assam',
    operatingHours: '5,320 hrs',
    hoursToday: '12.5 hrs',
    fuelLevel: 74,
    engineTemp: '89°C (Normal)',
    batteryVoltage: '24.4 V',
    vibrationLevel: '1.1 mm/s (Optimal)',
    maintenanceDue: 'In 80 hrs',
    associatedAct: 'ACT-3088',
    telemetry: {
      gps: { lat: 27.3530, lng: 95.3160 },
      rpm: 1500,
      fuelRateLph: 42.1,
      outputFrequency: 50.0,
      lineVoltage: 415,
      powerFactor: 0.85,
      engineLoadPct: 76,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '2 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-DGSET-03',
    projectId,
    name: 'Caterpillar C13 400 kVA Mobile Power Gen',
    category: 'DG_SET',
    categoryName: 'DG sets',
    tag: 'High-Pressure Hydrotesting Pumps Power',
    operator: 'Manabendra Sarma',
    status: 'STANDBY',
    location: 'Hydrotest Manifold Point 01',
    operatingHours: '2,110 hrs',
    hoursToday: '1.0 hrs',
    fuelLevel: 95,
    engineTemp: '75°C (Normal)',
    batteryVoltage: '24.8 V',
    vibrationLevel: '0.5 mm/s (Optimal)',
    maintenanceDue: 'In 320 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3585, lng: 95.3260 },
      rpm: 1500,
      fuelRateLph: 12.0,
      outputFrequency: 50.2,
      lineVoltage: 415,
      powerFactor: 0.91,
      engineLoadPct: 18,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '8 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-DGSET-04',
    projectId,
    name: 'Ashok Leyland 125 kVA Acoustic Trailer DG',
    category: 'DG_SET',
    categoryName: 'DG sets',
    tag: 'Radiography Darkroom & NDT Van Power',
    operator: 'Sarat Medhi',
    status: 'ACTIVE',
    location: 'NDT Inspection Field Base (Chainage 14+900)',
    operatingHours: '3,490 hrs',
    hoursToday: '8.5 hrs',
    fuelLevel: 60,
    engineTemp: '86°C (Normal)',
    batteryVoltage: '24.2 V',
    vibrationLevel: '0.8 mm/s (Optimal)',
    maintenanceDue: 'In 190 hrs',
    associatedAct: 'PIP-L5-024',
    telemetry: {
      gps: { lat: 27.3524, lng: 95.3138 },
      rpm: 1500,
      fuelRateLph: 16.2,
      outputFrequency: 49.9,
      lineVoltage: 415,
      powerFactor: 0.89,
      engineLoadPct: 54,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '3 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-DGSET-05',
    projectId,
    name: 'Kohler-SDMO 500 kVA Containerized DG Unit',
    category: 'DG_SET',
    categoryName: 'DG sets',
    tag: 'Terminal Substation Emergency Black-Start',
    operator: 'Jitul Saikia',
    status: 'ACTIVE',
    location: 'Main Substation 33kV Yard',
    operatingHours: '1,880 hrs',
    hoursToday: '9.2 hrs',
    fuelLevel: 86,
    engineTemp: '88°C (Normal)',
    batteryVoltage: '24.5 V',
    vibrationLevel: '0.9 mm/s (Optimal)',
    maintenanceDue: 'In 240 hrs',
    associatedAct: 'ELC-L5-042',
    telemetry: {
      gps: { lat: 27.3555, lng: 95.3200 },
      rpm: 1500,
      fuelRateLph: 55.0,
      outputFrequency: 50.0,
      lineVoltage: 415,
      powerFactor: 0.92,
      engineLoadPct: 62,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '1 min ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'EQ-DGSET-06',
    projectId,
    name: 'Mahindra Powerol 200 kVA Prime Industrial DG',
    category: 'DG_SET',
    categoryName: 'DG sets',
    tag: 'Dewatering Pumps & Night Mast Floodlights',
    operator: 'Naba Kumar Nath',
    status: 'ACTIVE',
    location: 'Pier 25 Foundation Cofferdam',
    operatingHours: '3,780 hrs',
    hoursToday: '11.0 hrs',
    fuelLevel: 42,
    engineTemp: '91°C (Normal)',
    batteryVoltage: '24.1 V',
    vibrationLevel: '1.2 mm/s (Acceptable)',
    maintenanceDue: 'In 70 hrs',
    associatedAct: 'CIV-L5-019',
    telemetry: {
      gps: { lat: 27.3565, lng: 95.3218 },
      rpm: 1500,
      fuelRateLph: 24.0,
      outputFrequency: 50.1,
      lineVoltage: 415,
      powerFactor: 0.86,
      engineLoadPct: 70,
      connectivity: '4G_IOT_CONNECTED',
      lastHeartbeat: '2 mins ago',
    },
    createdAt: '2026-09-01T08:00:00.000Z',
  },
];
