import { 
  Project, 
  WBSNode, 
  ScheduleActivity, 
  InformalSiteUpdate, 
  ConflictItem, 
  WorkerProfile, 
  MaterialTransaction, 
  AuditRecord,
  UserProfile 
} from '../types';

export const CURRENT_USER: UserProfile = {
  id: 'USR-8812',
  name: 'Marcus Vance, P.E.',
  email: 'm.vance@apexbuild.epc',
  role: 'PROJECT_DIRECTOR',
  discipline: 'Project Controls & Engineering',
  organization: 'ApexBuild EPC Consortium',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  fidicDesignation: "Engineer's Representative (FIDIC 3.1)",
  currentProjectRole: 'Project Director & Controls Lead',
};

export const INITIAL_PROJECT: Project = {
  id: 'PRJ-8840',
  code: 'APX-PRJ-094',
  name: 'Terminal Expansion & Crude Oil Trunk Pipeline Package II',
  client: 'Oil India Limited (OIL)',
  contractorJV: 'Central Viaduct & Petro-Infrastructure JV',
  contractType: 'FIDIC Red Book Cl. 8.4',
  lifecycle: 'EXECUTION',
  location: 'Duliajan - Digboi Terminal Corridor, Assam',
  budget: 245000000,
  currency: 'INR (₹ Cr)',
  startDate: '2026-01-15',
  plannedFinishDate: '2026-11-30',
  spi: 1.04,
  cpi: 0.98,
  evidenceCoverage: 91.6,
  telemetryFreshness: 88.0,
  status: 'ON_TRACK',
};

export const INITIAL_WBS: WBSNode[] = [
  { id: 'WBS-1', code: '01', name: 'Mobilization, Surveys & Enabling Works', level: 1, discipline: 'CIVIL' },
  { id: 'WBS-2', code: '02', name: 'Terminal Facility Foundations & Civil Works', level: 1, discipline: 'CIVIL' },
  { id: 'WBS-3', code: '03', name: 'Pipeline Corridor & Transfer Utilities', level: 1, discipline: 'PIPING' },
  { id: 'WBS-4', code: '03.02', name: 'Corridor Section 2 - Viaduct & Crossings', level: 2, parentId: 'WBS-3', discipline: 'PIPING' },
  { id: 'WBS-5', code: '03.02.04', name: 'WP-104 Pier 24-26 Foundations & Line 24 Trunk', level: 3, parentId: 'WBS-4', discipline: 'PIPING' },
  { id: 'WBS-6', code: '04', name: 'Electrical Substation & Cathodic Protection', level: 1, discipline: 'ELECTRICAL' },
  { id: 'WBS-7', code: '05', name: 'SCADA, Telemetry & Metering Station', level: 1, discipline: 'INSTRUMENTATION' },
  { id: 'WBS-8', code: '06', name: 'Pre-Commissioning, Hydrotesting & Handover', level: 1, discipline: 'COMMISSIONING' },
];

export const INITIAL_ACTIVITIES: ScheduleActivity[] = [
  {
    id: 'ACT-PIP-024',
    activityCode: 'PIP-L5-024',
    uwid: 'UWID-OIL-2026-PIP024',
    wbsId: 'WBS-5',
    wbsCode: '03.02.04',
    name: 'Pipe Installation — Trunk Line 24 (12" Crude Transfer)',
    description: 'Fit-up, stringing, automatic orbital welding, NDT radiography, field joint coating, and trench lower-in for 12-inch API 5L X52 pipe section.',
    discipline: 'PIPING',
    plannedStart: '2026-09-10',
    plannedFinish: '2026-09-28',
    durationDays: 18,
    totalFloatDays: 2,
    isCriticalPath: true,
    predecessorCodes: ['CIV-L5-019'],
    successorCodes: ['ELC-L5-042', 'ACT-HYD-008'],
    steps: [
      { id: 'STP-1', name: 'Pipe Stringing & Placement', weight: 20, completed: true, completionDate: '2026-09-14' },
      { id: 'STP-2', name: 'Fit-up & Root Pass Welding', weight: 30, completed: true, completionDate: '2026-09-20' },
      { id: 'STP-3', name: 'Hot, Fill & Cap Welding Passes', weight: 25, completed: false },
      { id: 'STP-4', name: '100% Radiographic Testing (RT) & NDT', weight: 15, completed: false },
      { id: 'STP-5', name: 'Joint Coating & Trench Lower-in', weight: 10, completed: false },
    ],
    plannedProgress: 75.0,
    contractorReportedProgress: 80.0,
    quantitySurveyProgress: 74.5,
    qcPassedProgress: 70.0,
    droneLidarProgress: 68.2,
    validatedConsensusProgress: 72.4,
    progressConfidence: 94.2,
    toleranceExceeded: true,
    deltaVsConsensus: 7.6, // Contractor 80% vs 72.4% Consensus (+7.6%)
    plannedQuantity: 420,
    installedQuantity: 304,
    unit: 'linear meters',
    assignedSupervisor: 'R. K. Sharma (Lead Piping Inspector)',
    workforceCount: 18,
    equipmentIds: ['EQ-CRANE-04', 'EQ-WELD-GEN-02', 'EQ-EXCAV-07'],
    materialCodes: ['MAT-PIPE-12X52', 'MAT-WELD-E7018', 'MAT-SLEEVE-12IN'],
    lastEvidenceUpdate: '4 hours ago',
    freshnessState: 'CURRENT',
  },
  {
    id: 'ACT-STR-3088',
    activityCode: 'ACT-3088',
    uwid: 'UWID-EXP-2024-03088',
    wbsId: 'WBS-5',
    wbsCode: '03.02.04',
    name: 'Segment B-14 Post-Tensioned Pier Cap (Pier 24-26)',
    description: 'Reinforced concrete post-tensioned pier cap construction using Fe500D rebar and C40/50 self-compacting concrete.',
    discipline: 'CIVIL',
    plannedStart: '2026-09-05',
    plannedFinish: '2026-09-25',
    durationDays: 20,
    totalFloatDays: 0,
    isCriticalPath: true,
    predecessorCodes: ['CIV-L5-018'],
    successorCodes: ['PIP-L5-024'],
    steps: [
      { id: 'STP-11', name: 'Rebar Cage Fabrication', weight: 40, completed: true, completionDate: '2026-09-12' },
      { id: 'STP-12', name: 'Duct & Tendon Placement', weight: 20, completed: true, completionDate: '2026-09-16' },
      { id: 'STP-13', name: 'Formwork & Pre-pour Inspection', weight: 15, completed: true, completionDate: '2026-09-18' },
      { id: 'STP-14', name: 'Concrete Pouring (Batch #LB-2024-881)', weight: 15, completed: true, completionDate: '2026-09-20' },
      { id: 'STP-15', name: 'Post-tensioning Jacking (28-day break pending)', weight: 10, completed: false },
    ],
    plannedProgress: 85.0,
    contractorReportedProgress: 90.0,
    quantitySurveyProgress: 84.0,
    qcPassedProgress: 75.0, // Pending 28-day concrete cube compressive tests
    droneLidarProgress: 82.5,
    validatedConsensusProgress: 80.8,
    progressConfidence: 91.0,
    toleranceExceeded: true,
    deltaVsConsensus: 9.2,
    plannedQuantity: 180,
    installedQuantity: 148,
    unit: 'cu. meters',
    assignedSupervisor: 'A. K. Baruah (Senior Civil Engineer)',
    workforceCount: 24,
    equipmentIds: ['EQ-PUMP-01', 'EQ-BOOM-03'],
    materialCodes: ['MAT-REBAR-FE500D', 'MAT-CONC-C40'],
    lastEvidenceUpdate: '6 hours ago',
    freshnessState: 'CURRENT',
  },
  {
    id: 'ACT-CIV-019',
    activityCode: 'CIV-L5-019',
    uwid: 'UWID-OIL-2026-CIV019',
    wbsId: 'WBS-5',
    wbsCode: '03.02.04',
    name: 'Trench Excavation & Shoring (Chainage 14+200 to 14+850)',
    description: 'Mechanized trenching to 2.4m depth with sheet pile shoring and dewatering for pipe laying corridor.',
    discipline: 'CIVIL',
    plannedStart: '2026-08-25',
    plannedFinish: '2026-09-12',
    actualStart: '2026-08-26',
    actualFinish: '2026-09-13',
    durationDays: 18,
    totalFloatDays: 5,
    isCriticalPath: false,
    predecessorCodes: [],
    successorCodes: ['PIP-L5-024'],
    plannedProgress: 100.0,
    contractorReportedProgress: 100.0,
    quantitySurveyProgress: 100.0,
    qcPassedProgress: 100.0,
    droneLidarProgress: 99.8,
    validatedConsensusProgress: 100.0,
    progressConfidence: 99.2,
    toleranceExceeded: false,
    deltaVsConsensus: 0.0,
    plannedQuantity: 650,
    installedQuantity: 650,
    unit: 'meters',
    assignedSupervisor: 'M. Gogoi (Site Foreman)',
    workforceCount: 12,
    equipmentIds: ['EQ-EXCAV-07', 'EQ-DUMPER-03'],
    materialCodes: ['MAT-SHORING-STEEL'],
    lastEvidenceUpdate: '14 days ago',
    freshnessState: 'STALE',
  },
  {
    id: 'ACT-ELC-042',
    activityCode: 'ELC-L5-042',
    uwid: 'UWID-OIL-2026-ELC042',
    wbsId: 'WBS-6',
    wbsCode: '04',
    name: 'Impressed Current Cathodic Protection (ICCP) & Test Posts',
    description: 'Deep well anode bed installation, cable laying, and test post hookup for corrosion mitigation.',
    discipline: 'ELECTRICAL',
    plannedStart: '2026-09-26',
    plannedFinish: '2026-10-15',
    durationDays: 19,
    totalFloatDays: 4,
    isCriticalPath: false,
    predecessorCodes: ['PIP-L5-024'],
    successorCodes: ['ACT-HYD-008'],
    plannedProgress: 15.0,
    contractorReportedProgress: 15.0,
    quantitySurveyProgress: 14.0,
    qcPassedProgress: 12.0,
    droneLidarProgress: 13.0,
    validatedConsensusProgress: 13.5,
    progressConfidence: 89.0,
    toleranceExceeded: false,
    deltaVsConsensus: 1.5,
    plannedQuantity: 12,
    installedQuantity: 2,
    unit: 'stations',
    assignedSupervisor: 'S. K. Paul (Electrical Lead)',
    workforceCount: 8,
    equipmentIds: ['EQ-DRILL-02'],
    materialCodes: ['MAT-ANODE-MMO', 'MAT-CABLE-XLPE'],
    lastEvidenceUpdate: '1 day ago',
    freshnessState: 'RECENT',
  },
];

export const INITIAL_CONFLICTS: ConflictItem[] = [
  {
    id: 'CONF-01',
    activityCode: 'PIP-L5-024',
    activityName: 'Pipe Installation — Trunk Line 24',
    type: 'PROGRESS_VARIANCE',
    severity: 'CRITICAL',
    title: 'Contractor Claim vs Point Cloud LiDAR Delta (+11.8%)',
    description: 'Contractor monthly submittal claims 80.0% pipe welding complete, whereas LiDAR point cloud (Mission FL-094-14) calculates placed volume at 68.2%. Tolerance limit of ±5.0% breached.',
    varianceValue: '+11.8% over LiDAR',
    claimedValue: '80.0% (Contractor IPC #14)',
    verifiedValue: '68.2% (LiDAR Point Cloud)',
    specOrClause: 'FIDIC Cl. 14.3 / Specs Sec. 04.2',
    timestamp: '2 hours ago',
    actionRequired: 'Joint field reconciliation walk with QS & Drone Survey lead.',
    status: 'OPEN',
  },
  {
    id: 'CONF-02',
    activityCode: 'ACT-3088',
    activityName: 'Segment B-14 Post-Tensioned Pier Cap',
    type: 'SILENT_RISK',
    severity: 'HIGH',
    title: 'Silent Risk: Unverified Structural Concrete Core (28-day cube break)',
    description: 'Contractor claimed 90% progress on Pier 24 cap, but 3rd-party concrete core compression tests (Set #09B, 28-day break) remain pending in QA/QC Materials Lab. Cannot approve post-tensioning release.',
    varianceValue: '-4 Days Critical Path impact',
    claimedValue: 'Pour Complete (90%)',
    verifiedValue: 'Lab Batch LB-2024-881 Pending',
    specOrClause: 'ASTM C39 / C40-50 & FIDIC Cl. 4.12',
    timestamp: '5 hours ago',
    actionRequired: 'Request expedited lab break certificate from NABL lab.',
    status: 'INVESTIGATING',
  },
  {
    id: 'CONF-03',
    activityCode: 'PIP-L5-024',
    activityName: 'Pipe Installation — Trunk Line 24',
    type: 'MATERIAL_SHORTAGE',
    severity: 'MEDIUM',
    title: 'Supply Chain Bottleneck: Missing 12" Heavy Wall Elbow Spools',
    description: 'Activity requires 14 units of 12" X52 90-degree forged elbows. Only 8 units verified in Zone B warehouse (GRN-2026-441). Shortage of 6 units will halt tie-in next Tuesday.',
    varianceValue: '6 Spools Short',
    claimedValue: '14 Required',
    verifiedValue: '8 in Stores',
    specOrClause: 'API 5L / ASME B16.9',
    timestamp: '1 day ago',
    actionRequired: 'Expedite vendor dispatch from L&T Heavy Engineering Hazira.',
    status: 'OPEN',
  },
];

export const INITIAL_INFORMAL_UPDATES: InformalSiteUpdate[] = [
  {
    id: 'UPD-101',
    source: 'VOICE_HINDI',
    rawInput: 'Line 24 ka pipe installation start ho gaya hai, 45 meter welding complete hai, lekin material delay ki wajah se do joints pending hain.',
    timestamp: 'Today, 10:45 AM',
    reportedBy: 'Vikram Joshi (Site Supervisor)',
    supervisorRole: 'Site Piping Supervisor',
    locationGeofence: 'Chainage 14+450 (Within 15m radius)',
    extractedEntities: {
      discipline: 'PIPING',
      lineOrTag: 'Line 24',
      action: 'pipe installation & welding',
      quantity: 45,
      unit: 'meters',
      progressPercentage: 68,
      delayReason: 'Missing 12" forged elbow spools from warehouse',
      materialsMentioned: ['12" X52 Pipe', 'Welding Electrodes E7018'],
    },
    matchedActivityId: 'ACT-PIP-024',
    matchedActivityCode: 'PIP-L5-024',
    matchedActivityName: 'Pipe Installation — Trunk Line 24 (12" Crude Transfer)',
    linkingConfidence: 0.98,
    isOutOfSequence: false,
    linkingStatus: 'CONFIRMED',
  },
  {
    id: 'UPD-102',
    source: 'WHATSAPP',
    rawInput: 'Pier 24 cap shuttering open kar di hai. Rebar clear hai. Pre-pour QA checklist signed by client rep.',
    timestamp: 'Today, 08:30 AM',
    reportedBy: 'K. N. Saikia (Civil Supervisor)',
    supervisorRole: 'Civil Site Engineer',
    locationGeofence: 'Pier 24 Location Coordinates (Assam)',
    extractedEntities: {
      discipline: 'CIVIL',
      lineOrTag: 'Pier 24',
      action: 'shuttering & rebar inspection',
      progressPercentage: 85,
    },
    matchedActivityId: 'ACT-STR-3088',
    matchedActivityCode: 'ACT-3088',
    matchedActivityName: 'Segment B-14 Post-Tensioned Pier Cap (Pier 24-26)',
    linkingConfidence: 0.94,
    isOutOfSequence: false,
    linkingStatus: 'CONFIRMED',
  },
];

export const INITIAL_WORKERS: WorkerProfile[] = [
  {
    id: 'WRK-101',
    badgeNumber: 'LAB-IND-0442',
    name: 'Tapan Das',
    trade: 'WELDER',
    skills: ['6G Pipe TIG/MIG', 'API 1104 Certified', 'SMAW Downhill'],
    contractor: 'PetroFab Infrastructure Ltd',
    activeProject: 'PRJ-8840',
    assignedActivityId: 'ACT-PIP-024',
    safetyCertValidTill: '2027-04-15',
    medicalClearance: true,
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    lastClockIn: '07:45 AM (Gate 3 Geofence)',
    attendanceStatus: 'VERIFIED_PRESENT',
    verificationMethod: 'GEOFENCE_BIOMETRIC',
    confidenceScore: 98,
  },
  {
    id: 'WRK-102',
    badgeNumber: 'LAB-IND-0443',
    name: 'Sunil Karmakar',
    trade: 'FITTER',
    skills: ['Pipe Fitting 12"-24"', 'Cold Cutting', 'Beveling Prep'],
    contractor: 'PetroFab Infrastructure Ltd',
    activeProject: 'PRJ-8840',
    assignedActivityId: 'ACT-PIP-024',
    safetyCertValidTill: '2026-12-30',
    medicalClearance: true,
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    lastClockIn: '07:48 AM (Gate 3 Geofence)',
    attendanceStatus: 'VERIFIED_PRESENT',
    verificationMethod: 'GEOFENCE_BIOMETRIC',
    confidenceScore: 96,
  },
  {
    id: 'WRK-103',
    badgeNumber: 'LAB-IND-0489',
    name: 'Biren Chetia',
    trade: 'OPERATOR',
    skills: ['Tadano 50T Rough Terrain Crane', 'Lifting Gear Inspector'],
    contractor: 'Heavy Rigging Trans',
    activeProject: 'PRJ-8840',
    assignedActivityId: 'ACT-PIP-024',
    safetyCertValidTill: '2027-01-10',
    medicalClearance: true,
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    lastClockIn: '08:10 AM (Manual Entry by Supervisor)',
    attendanceStatus: 'PRESENT_NEEDS_REVIEW',
    verificationMethod: 'SUPERVISOR_ROSTER',
    confidenceScore: 68,
  },
];

export const INITIAL_MATERIALS: MaterialTransaction[] = [
  {
    id: 'TX-GRN-441',
    docType: 'GRN',
    docNumber: 'GRN-2026-441',
    materialCode: 'MAT-PIPE-12X52',
    description: '12" Seamless Carbon Steel Line Pipe, API 5L Gr. X52 PSL2 (12.7mm WT)',
    quantity: 120,
    unit: 'meters (10 spools)',
    sourceSupplier: 'Welspun Corp Ltd, Gujarat',
    destinationLocation: 'Central Terminal Pipe Yard (Zone B)',
    associatedActivityCode: 'PIP-L5-024',
    date: '2026-09-24',
    status: 'INSPECTED_ACCEPTED',
  },
  {
    id: 'TX-GIN-812',
    docType: 'GIN',
    docNumber: 'GIN-2026-812',
    materialCode: 'MAT-PIPE-12X52',
    description: '12" Seamless Line Pipe issued to Field Trenching Gang',
    quantity: 60,
    unit: 'meters (5 spools)',
    sourceSupplier: 'Zone B Stores',
    destinationLocation: 'Line 24 Trench Chainage 14+300',
    associatedActivityCode: 'PIP-L5-024',
    issuedToSupervisor: 'Vikram Joshi (Site Supervisor)',
    date: '2026-09-28',
    status: 'DISPATCHED',
  },
];

export const INITIAL_AUDIT_LOGS: AuditRecord[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-09-29 10:48:12 IST',
    actorName: 'Vikram Joshi',
    actorRole: 'Site Piping Supervisor',
    action: 'VOICE_UPDATE_LINKED',
    entityType: 'ACTIVITY',
    entityId: 'PIP-L5-024',
    previousValue: 'Progress 65.0%',
    newValue: 'Progress 68.0% (45m installed)',
    reason: 'Voice note parsed and linked: Field orbital welding progress confirmed with joint numbers #W24-01 to #W24-06.',
    ipOrDevice: 'Handheld Mobile Device (Geo: 27.3512° N, 95.3124° E)',
  },
  {
    id: 'AUD-002',
    timestamp: '2026-09-29 11:15:00 IST',
    actorName: 'Triangulation Engine',
    actorRole: 'Automated Truth Reconciler',
    action: 'CONSENSUS_RECALCULATED',
    entityType: 'PROGRESS',
    entityId: 'PIP-L5-024',
    previousValue: '71.5%',
    newValue: '72.4%',
    reason: 'Multi-factor algorithm recalculated with updated field surveyor measurement (+2.1% QS adjustment).',
    ipOrDevice: 'ApexBuild Cloud Engine Node-01',
  },
  {
    id: 'AUD-003',
    timestamp: '2026-09-29 11:30:24 IST',
    actorName: 'Marcus Vance, P.E.',
    actorRole: "Engineer's Representative (FIDIC 3.1)",
    action: 'CONFLICT_FLAGGED',
    entityType: 'CONFLICT',
    entityId: 'CONF-01',
    previousValue: 'None',
    newValue: 'CRITICAL Progress Variance (+11.8%)',
    reason: 'Flagged variance between contractor monthly claim (80%) and drone LiDAR scan (68.2%). Requested joint walk.',
    ipOrDevice: 'Workstation Mac OS (Client IP 103.22.45.19)',
  },
];
