import 'language_controller.dart';

class AppLanguage {
  final String code;
  final String name;
  final String nativeName;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
  });
}

class AppLocalizations {
  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'en', name: 'English', nativeName: 'English'),
    AppLanguage(code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'),
    AppLanguage(code: 'te', name: 'Telugu', nativeName: 'తెలుగు'),
    AppLanguage(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'),
    AppLanguage(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'),
    AppLanguage(code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'),
    AppLanguage(code: 'mr', name: 'Marathi', nativeName: 'मराठी'),
    AppLanguage(code: 'bn', name: 'Bengali', nativeName: 'বাংলা'),
    AppLanguage(code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'),
    AppLanguage(code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'),
    AppLanguage(code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ'),
    AppLanguage(code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ'),
    AppLanguage(code: 'ur', name: 'Urdu', nativeName: 'اردو'),
    AppLanguage(code: 'mai', name: 'Maithili', nativeName: 'मैथिली'),
    AppLanguage(code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्'),
  ];

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Nirmaan OS',
      'tagline': 'Industrial Project Management & AI Intelligence Platform',
      'project_workspace': 'Project Workspace',
      'unique_id': 'Project Unique ID',
      'expected_completion': 'Expected Completion Date',
      'original_finish': 'Original Contract Finish',
      'variance': 'Schedule Slippage Variance',
      'budget_tracking': 'Budget & Expenditure Tracking',
      'total_budget': 'Total Sanctioned Budget',
      'spent_budget': 'Amount Expanded / Spent',
      'remaining_budget': 'Remaining Funds',
      'daily_update': 'Daily Cost & Progress Update',
      'schedule_forecast': 'Schedule Delay & Forecast Engine',
      'hr_workforce': 'HR & Digital Workforce',
      'labour_attendance': 'Verified Labour Attendance',
      'supervisor_visit': 'Site Supervisor Proof of Presence',
      'voice_assistant': 'AI Voice Assistant (Hands-Free)',
      'pdf_intelligence': 'Tender PDF Summary & 1-to-1 Translation',
      'gemini_brain': 'Gemini AI Autonomous Brain',
      'clock_in': 'Verify GPS Geofenced Attendance',
      'mark_presence': 'Capture Verified Site Visit',
      'review_and_confirm': 'Review & Confirm Update',
      'speak_now': 'Speak in Hindi or English...',
      'tender_summary': 'Tender Executive Summary',
      'convert_to_hindi': 'Page-Preserving Hindi Translation (90p -> 90p)',
      'materials_stores': 'Stores Ledger (GRN / GIN)',
      'conflicts_disputes': 'FIDIC Conflict & Dispute Center',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC Variations',
      'fidic_variations_subtitle': 'Scope Change & Variation Register',
      'variation_orders': 'Variation Orders & Scope Changes',
      'clause_13_variations': 'FIDIC Clause 13 Variations',
      'claims_dab': 'Claims & DAB',
      'claims_dab_subtitle': 'Dispute Adjudication & Delay Claims',
      'extension_of_time': 'Extension of Time (EOT)',
      'dispute_adjudication': 'Dispute Adjudication Board (DAB)',
      'pipeline_ndt': 'Pipeline NDT',
      'pipeline_ndt_subtitle': 'Radiographic Inspection & Weld Clearance',
      'weld_integrity': 'Weld Integrity & Radiography',
      'ndt_clearance': 'Pipeline NDT Clearance',
      'digital_twin': 'Digital Twin',
      'digital_twin_subtitle': 'Oil India Duliajan GIS & 3D Layout',
      'gis_site_map': '3D GIS Digital Twin Map',
      'chainage_tracking': 'Pipeline Chainage Tracking',
      'executive_reports': 'Executive Reports',
      'executive_reports_subtitle': 'PDF Dossier, Health Index & Export',
      'health_index': 'Project Health Index',
      'dossier_export': 'Executive Progress Dossier',
      'stakeholder_portal': 'Stakeholder Portal',
      'stakeholder_portal_subtitle': 'Client, EPC, TPIA & Foreman Hub',
      'contractor_hub': 'EPC & Subcontractor Hub',
      'hold_point_approvals': 'Quality Hold Point Approvals',
    },
    'hi': {
      'app_title': 'निर्माण ओएस',
      'tagline': 'औद्योगिक परियोजना प्रबंधन एवं एआई इंटेलिजेंस प्लेटफॉर्म',
      'project_workspace': 'प्रोजेक्ट वर्कस्पेस',
      'unique_id': 'प्रोजेक्ट यूनिक आईडी',
      'expected_completion': 'अनुमानित पूर्ण होने की तिथि',
      'original_finish': 'मूल अनुबंध समाप्ति तिथि',
      'variance': 'अनुसूची में देरी (वेरिएंस)',
      'budget_tracking': 'बजट एवं व्यय ट्रैकिंग',
      'total_budget': 'कुल स्वीकृत बजट',
      'spent_budget': 'अब तक खर्च की गई राशि',
      'remaining_budget': 'शेष उपलब्ध बजट',
      'daily_update': 'दैनिक लागत व प्रगति अपडेट',
      'schedule_forecast': 'शेड्यूल देरी एवं पूर्वानुमान इंजन',
      'hr_workforce': 'एचआर एवं डिजिटल कार्यबल',
      'labour_attendance': 'सत्यापित श्रमिक उपस्थिति',
      'supervisor_visit': 'साइट सुपरवाइजर वास्तविक उपस्थिति प्रमाण',
      'voice_assistant': 'एआई वॉयस असिस्टेंट (हैंड्स-फ्री)',
      'pdf_intelligence': 'टेंडर पीडीएफ सारांश एवं 1-से-1 अनुवाद',
      'gemini_brain': 'जेमिनी एआई ऑटोनॉमस ब्रेन',
      'clock_in': 'जीपीएस जियोफेंस उपस्थिति सत्यापित करें',
      'mark_presence': 'सत्यापित साइट विजिट दर्ज करें',
      'review_and_confirm': 'समीक्षा करें एवं पुष्टि करें',
      'speak_now': 'हिंदी या अंग्रेजी में बोलें...',
      'tender_summary': 'टेंडर मुख्य निष्कर्ष सारांश',
      'convert_to_hindi': 'पेज-संरक्षित हिंदी अनुवाद (90 पेज -> 90 पेज)',
      'materials_stores': 'स्टोर्स लेजर (जीआरएन / जीआईएन)',
      'conflicts_disputes': 'एफआईडीआईसी विवाद समाधान केंद्र',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'एफआईडीआईसी बदलाव (FIDIC Variations)',
      'fidic_variations_subtitle': 'कार्यक्षेत्र परिवर्तन एवं बदलाव रजिस्टर',
      'variation_orders': 'परिवर्तन आदेश एवं कार्यक्षेत्र बदलाव',
      'clause_13_variations': 'एफआईडीआईसी क्लॉज 13 बदलाव रजिस्टर',
      'claims_dab': 'दावे एवं डीएबी (Claims & DAB)',
      'claims_dab_subtitle': 'विवाद अधिनिर्णय एवं देरी दावे',
      'extension_of_time': 'समय विस्तार दावा (EOT)',
      'dispute_adjudication': 'विवाद अधिनिर्णय बोर्ड (DAB)',
      'pipeline_ndt': 'पाइपलाइन एनडीटी (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'रेडियोग्राफिक परीक्षण एवं वेल्ड क्लीयरेंस',
      'weld_integrity': 'वेल्ड अखंडता एवं रेडियोग्राफी',
      'ndt_clearance': 'पाइपलाइन एनडीटी क्लीयरेंस',
      'digital_twin': 'डिजिटल ट्विन 3D (Digital Twin)',
      'digital_twin_subtitle': 'ऑयल इंडिया दुलियाजान जीआईएस एवं 3D लेआउट',
      'gis_site_map': '3D जीआईएस डिजिटल ट्विन मैप',
      'chainage_tracking': 'पाइपलाइन चेनेज ट्रैकिंग',
      'executive_reports': 'कार्यकारी रिपोर्ट (Executive Reports)',
      'executive_reports_subtitle': 'पीडीएफ डोजियर, स्वास्थ्य सूचकांक एवं निर्यात',
      'health_index': 'परियोजना स्वास्थ्य सूचकांक',
      'dossier_export': 'कार्यकारी प्रगति डोजियर',
      'stakeholder_portal': 'स्टेकहोल्डर पोर्टल (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'क्लाइंट, ईपीसी, टीपीआईए एवं फोरमैन हब',
      'contractor_hub': 'ईपीसी एवं ठेकेदार हब',
      'hold_point_approvals': 'गुणवत्ता होल्ड पॉइंट अनुमोदन',
    },
    'te': {
      'app_title': 'నిర్మాణ్ ఓఎస్',
      'tagline': 'పారిశ్రామిక ప్రాజెక్ట్ నిర్వహణ & AI ఇంటెలిజెన్స్',
      'project_workspace': 'ప్రాజెక్ట్ వర్క్‌స్పేస్',
      'unique_id': 'ప్రాజెక్ట్ ప్రత్యేక ఐడి',
      'expected_completion': 'పూర్తి అయ్యే అంచనా తేదీ',
      'original_finish': 'ప్రారంభ ఒప్పంద ముగింపు తేదీ',
      'variance': 'షెడ్యూల్ ఆలస్యం వ్యత్యాసం',
      'budget_tracking': 'బడ్జెట్ & ఖర్చుల ట్రాకింగ్',
      'total_budget': 'మొత్తం మంజూరైన బడ్జెట్',
      'spent_budget': 'ఇప్పటివరకు ఖర్చు చేసినది',
      'remaining_budget': 'మిగిలిన బడ్జెట్',
      'daily_update': 'రోజువారీ పురోగతి & ఖర్చు అప్‌డేట్',
      'schedule_forecast': 'షెడ్యూల్ ఆలస్యం & అంచనా వ్యవస్థ',
      'hr_workforce': 'హెచ్ఆర్ & శ్రామిక వర్గం',
      'labour_attendance': 'ధృవీకరించబడిన కార్మికుల హాజరు',
      'supervisor_visit': 'సైట్ సూపర్‌వైజర్ ఉనికి ధృవీకరణ',
      'voice_assistant': 'AI వాయిస్ అసిస్టెంట్',
      'pdf_intelligence': 'టెండర్ పిడిఎఫ్ సారాంశం & అనువాదం',
      'gemini_brain': 'జెమిని AI స్వయంప్రతిపత్తి బ్రెయిన్',
      'clock_in': 'GPS జియోఫెన్స్ హాజరు ధృవీకరించండి',
      'mark_presence': 'సైట్ విజిట్ నమోదు చేయండి',
      'review_and_confirm': 'సమీక్షించి నిర్ధారించండి',
      'speak_now': 'తెలుగు లేదా ఇంగ్లీషులో మాట్లాడండి...',
      'tender_summary': 'టెండర్ ముఖ్య అంశాల సారాంశం',
      'convert_to_hindi': 'పేజీల క్రమం మారకుండా అనువాదం',
      'materials_stores': 'స్టోర్స్ లెడ్జర్ (GRN / GIN)',
      'conflicts_disputes': 'వివాద పరిష్కార కేంద్రం',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC మార్పులు (FIDIC Variations)',
      'fidic_variations_subtitle': 'పరిధి మార్పు & వేరియేషన్ రిజిస్టర్',
      'variation_orders': 'మార్పు ఉత్తర్వులు & పరిధి సవరణలు',
      'clause_13_variations': 'FIDIC నిబంధన 13 మార్పుల రిజిస్టర్',
      'claims_dab': 'క్లెయిమ్‌లు & DAB (Claims & DAB)',
      'claims_dab_subtitle': 'వివాద పరిష్కారం & ఆలస్య క్లెయిమ్‌లు',
      'extension_of_time': 'సమయ పొడిగింపు క్లెయిమ్ (EOT)',
      'dispute_adjudication': 'వివాద పరిష్కార మండలి (DAB)',
      'pipeline_ndt': 'పైప్‌లైన్ NDT (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'రేడియోలాజికల్ పరీక్ష & వెల్డింగ్ అనుమతి',
      'weld_integrity': 'వెల్డింగ్ నాణ్యత & రేడియోగ్రఫీ',
      'ndt_clearance': 'పైప్‌లైన్ NDT క్లియరెన్స్',
      'digital_twin': 'డిజిటల్ ట్విన్ 3D (Digital Twin)',
      'digital_twin_subtitle': 'ఆయిల్ ఇండియా దులియాజాన్ GIS & 3D లేఅవుట్',
      'gis_site_map': '3D GIS డిజిటల్ ట్విన్ మ్యాప్',
      'chainage_tracking': 'పైప్‌లైన్ చైనేజ్ ట్రాకింగ్',
      'executive_reports': 'కార్యనిర్వాహక నివేదికలు (Executive Reports)',
      'executive_reports_subtitle': 'PDF డాక్యుమెంట్, హెల్త్ ఇండెక్స్ & ఎగుమతి',
      'health_index': 'ప్రాజెక్ట్ హెల్త్ ఇండెక్స్',
      'dossier_export': 'కార్యనిర్వాహక పురోగతి డాక్యుమెంట్',
      'stakeholder_portal': 'స్టేక్‌హోల్డర్ పోర్టల్ (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'క్లయింట్, EPC, TPIA & ఫోర్‌మెన్ హబ్',
      'contractor_hub': 'EPC & కాంట్రాక్టర్ల కేంద్రం',
      'hold_point_approvals': 'నాణ్యత హోల్డ్ పాయింట్ ఆమోదాలు',
    },
    'ta': {
      'app_title': 'நிர்மான் ஓஎஸ்',
      'tagline': 'தொழில்துறை திட்ட மேலாண்மை மற்றும் AI நுண்ணறிவு',
      'project_workspace': 'திட்ட பணியிடம்',
      'unique_id': 'திட்ட தனித்துவ ஐடி',
      'expected_completion': 'எதிர்பார்க்கப்படும் முடிவு தேதி',
      'original_finish': 'அசல் ஒப்பந்த முடிவு தேதி',
      'variance': 'திட்ட காலதாமத வேறுபாடு',
      'budget_tracking': 'பட்ஜெட் மற்றும் செலவு கண்காணிப்பு',
      'total_budget': 'மொத்த அனுமதிக்கப்பட்ட பட்ஜெட்',
      'spent_budget': 'செலவழிக்கப்பட்ட தொகை',
      'remaining_budget': 'மீதமுள்ள நிதி',
      'daily_update': 'தினசரி செலவு மற்றும் முன்னேற்ற விவரம்',
      'schedule_forecast': 'காலதாமத முன்னறிவிப்பு அமைப்பு',
      'hr_workforce': 'மனிதவளம் மற்றும் டிஜிட்டல் தொழிலாளர்கள்',
      'labour_attendance': 'சரிபார்க்கப்பட்ட தொழிலாளர் வருகை',
      'supervisor_visit': 'மேற்பார்வையாளர் தள வருகை சரிபார்ப்பு',
      'voice_assistant': 'AI குரல் உதவியாளர்',
      'pdf_intelligence': 'டெண்டர் PDF சுருக்கம் & மொழிபெயர்ப்பு',
      'gemini_brain': 'ஜெமினி AI மூளை',
      'clock_in': 'GPS வருகையை சரிபார்க்கவும்',
      'mark_presence': 'தள வருகையை பதிவு செய்',
      'review_and_confirm': 'சரிபார்த்து உறுதிப்படுத்தவும்',
      'speak_now': 'பேசவும்...',
      'tender_summary': 'முக்கிய அம்சங்களின் சுருக்கம்',
      'convert_to_hindi': 'பக்க அமைப்பு மாறாத மொழிபெயர்ப்பு',
      'materials_stores': 'பொருள் இருப்பு விவரம்',
      'conflicts_disputes': 'தகராறு தீர்வு மையம்',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC மாற்றங்கள் (FIDIC Variations)',
      'fidic_variations_subtitle': 'திட்ட அளவு மாற்றம் & பதிவேடு',
      'variation_orders': 'மாறுதல் ஆணைகள் & திட்ட மாற்றங்கள்',
      'clause_13_variations': 'FIDIC விதி 13 மாற்றங்கள் பதிவேடு',
      'claims_dab': 'கோரிக்கைகள் & DAB (Claims & DAB)',
      'claims_dab_subtitle': 'தகராறு தீர்ப்பு & காலதாமதக் கோரிக்கைகள்',
      'extension_of_time': 'கால நீட்டிப்பு கோரிக்கை (EOT)',
      'dispute_adjudication': 'தகராறு தீர்ப்பு வாரியம் (DAB)',
      'pipeline_ndt': 'குழாய்த்தொடர் NDT (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'கதிரியக்க சோதனை & வெல்டிங் அனுமதி',
      'weld_integrity': 'வெல்டிங் தரம் & ரேடியோகிராபி',
      'ndt_clearance': 'குழாய்த்தொடர் NDT அனுமதி',
      'digital_twin': 'டிஜிட்டல் இரட்டை (Digital Twin 3D)',
      'digital_twin_subtitle': 'ஆயில் இந்தியா துலியாஜான் GIS & 3D வரைபடம்',
      'gis_site_map': '3D GIS டிஜிட்டல் வரைபடம்',
      'chainage_tracking': 'குழாய்த்தொடர் தூரக் கண்காணிப்பு',
      'executive_reports': 'நிர்வாக அறிக்கைகள் (Executive Reports)',
      'executive_reports_subtitle': 'PDF அறிக்கை, திட்ட நலக் குறியீடு & ஏற்றுமதி',
      'health_index': 'திட்ட சுகாதாரக் குறியீடு',
      'dossier_export': 'நிர்வாக முன்னேற்ற ஆவணம்',
      'stakeholder_portal': 'பங்குதாரர் தளம் (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'கிளையன்ட், EPC, TPIA & ஃபோர்மேன் மையம்',
      'contractor_hub': 'EPC & ஒப்பந்ததாரர் மையம்',
      'hold_point_approvals': 'தர ஆய்வு நிறுத்துப்புள்ளி ஒப்புதல்கள்',
    },
    'mr': {
      'app_title': 'निर्माण ओएस',
      'tagline': 'औद्योगिक प्रकल्प व्यवस्थापन आणि AI बुद्धिमत्ता',
      'project_workspace': 'प्रकल्प कार्यक्षेत्र',
      'unique_id': 'प्रकल्प युनिक आयडी',
      'expected_completion': 'अपेक्षित पूर्ण होण्याची तारीख',
      'original_finish': 'मूळ कराराची समाप्ती तारीख',
      'variance': 'वेळेतील विलंब फरक',
      'budget_tracking': 'बजेट आणि खर्च ट्रॅकिंग',
      'total_budget': 'एकूण मंजूर बजेट',
      'spent_budget': 'आतापर्यंत झालेला खर्च',
      'remaining_budget': 'शिल्लक उपलब्ध निधी',
      'daily_update': 'दैनिक खर्च आणि प्रगती अपडेट',
      'schedule_forecast': 'विलंब अंदाज आणि विश्लेषण',
      'hr_workforce': 'एचआर आणि कामगार व्यवस्थापन',
      'labour_attendance': 'प्रमाणित कामगार उपस्थिती',
      'supervisor_visit': 'सुपरवायझर प्रत्यक्ष उपस्थिती पडताळणी',
      'voice_assistant': 'AI व्हॉईस असिस्टंट',
      'pdf_intelligence': 'निविदा PDF सारांश आणि भाषांतर',
      'gemini_brain': 'जेमिनी AI स्वायत्त मेंदू',
      'clock_in': 'GPS द्वारे उपस्थिती नोंदवा',
      'mark_presence': 'साइट भेट नोंदवा',
      'review_and_confirm': 'तपासा आणि पुष्टी करा',
      'speak_now': 'मराठी किंवा इंग्रजीत बोला...',
      'tender_summary': 'निविदा मुख्य मुद्दे सारांश',
      'convert_to_hindi': 'पृष्ठ रचना न बदलता भाषांतर',
      'materials_stores': 'साठा नोंदवही (GRN / GIN)',
      'conflicts_disputes': 'विवाद निवारण केंद्र',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC बदल (FIDIC Variations)',
      'fidic_variations_subtitle': 'कार्यक्षेत्र बदल आणि व्हेरिएशन नोंदवही',
      'variation_orders': 'बदल आदेश आणि कार्यक्षेत्र विस्तार',
      'clause_13_variations': 'FIDIC क्लॉज 13 बदल नोंदवही',
      'claims_dab': 'दावे आणि डीएबी (Claims & DAB)',
      'claims_dab_subtitle': 'विवाद लवाद आणि विलंब दावे',
      'extension_of_time': 'मुदतवाढ दावा (EOT)',
      'dispute_adjudication': 'विवाद लवाद मंडळ (DAB)',
      'pipeline_ndt': 'पाईपलाईन एनडीटी (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'रेडिओग्राफिक चाचणी आणि वेल्ड मंजुरी',
      'weld_integrity': 'वेल्ड अखंडता आणि रेडियोग्राफी',
      'ndt_clearance': 'पाईपलाईन एनडीटी मंजुरी',
      'digital_twin': 'डिजिटल ट्विन 3D (Digital Twin)',
      'digital_twin_subtitle': 'ऑइल इंडिया दुलियाजान जीआयएस आणि 3D लेआउट',
      'gis_site_map': '3D जीआयएस डिजिटल ट्विन नकाशा',
      'chainage_tracking': 'पाईपलाईन चेनेज ट्रॅकिंग',
      'executive_reports': 'कार्यकारी अहवाल (Executive Reports)',
      'executive_reports_subtitle': 'पीडीएफ दस्तऐवज, आरोग्य निर्देशांक आणि निर्यात',
      'health_index': 'प्रकल्प आरोग्य निर्देशांक',
      'dossier_export': 'कार्यकारी प्रगती दस्तऐवज',
      'stakeholder_portal': 'भागधारक पोर्टल (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'क्लायंट, ईपीसी, टीपीआयए आणि फोरमन हब',
      'contractor_hub': 'ईपीसी आणि कंत्राटदार केंद्र',
      'hold_point_approvals': 'गुणवत्ता तपासणी बिंदू मंजुरी',
    },
    'bn': {
      'app_title': 'নির্মাণ ওএস',
      'tagline': 'শিল্প প্রকল্প পরিচালনা এবং এআই প্ল্যাটফর্ম',
      'project_workspace': 'প্রকল্প কর্মক্ষেত্র',
      'unique_id': 'প্রকল্পের অনন্য আইডি',
      'expected_completion': 'সমাপ্তির আনুমানিক তারিখ',
      'original_finish': 'মূল চুক্তি সমাপ্তির তারিখ',
      'variance': 'সময়সীমার বিলম্ব বৈষম্য',
      'budget_tracking': 'বাজেট এবং ব্যয় ট্র্যাকিং',
      'total_budget': 'মোট অনুমোদিত বাজেট',
      'spent_budget': 'ব্যয়িত মোট অর্থ',
      'remaining_budget': 'অবশিষ্ট বাজেট',
      'daily_update': 'দৈনিক অগ্রগতি ও ব্যয় আপডেট',
      'schedule_forecast': 'বিলম্ব পূর্বাভাস ব্যবস্থা',
      'hr_workforce': 'এইচআর ও ডিজিটাল কর্মীদল',
      'labour_attendance': 'যাচাইকৃত কর্মী উপস্থিতি',
      'supervisor_visit': 'সাইট সুপারভাইজার উপস্থিতি যাচাই',
      'voice_assistant': 'এআই ভয়েস সহকারী',
      'pdf_intelligence': 'টেন্ডার পিডিএফ সারাংশ ও অনুবাদ',
      'gemini_brain': 'জেমিনি এআই ব্রেন',
      'clock_in': 'জিপিএস উপস্থিতি নিশ্চিত করুন',
      'mark_presence': 'সাইট উপস্থিতি রেকর্ড করুন',
      'review_and_confirm': 'পর্যালোচনা ও নিশ্চিত করুন',
      'speak_now': 'বাংলা বা ইংরেজিতে বলুন...',
      'tender_summary': 'টেন্ডার মূল সারসংক্ষেপ',
      'convert_to_hindi': 'পৃষ্ঠা বিন্যাস অক্ষুণ্ণ অনুবাদ',
      'materials_stores': 'স্টোর লেজার (GRN / GIN)',
      'conflicts_disputes': 'বিরোধ নিষ্পত্তি কেন্দ্র',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'এফআইডিআইসি পরিবর্তন (FIDIC Variations)',
      'fidic_variations_subtitle': 'কার্যপরিধি পরিবর্তন ও ভ্যারিয়েশন রেজিস্টার',
      'variation_orders': 'পরিবর্তন আদেশ ও পরিধি সংশোধন',
      'clause_13_variations': 'এফআইডিআইসি ক্লজ ১৩ পরিবর্তন রেজিস্টার',
      'claims_dab': 'দাবি ও ডিএবি (Claims & DAB)',
      'claims_dab_subtitle': 'বিরোধ নিষ্পত্তি ও বিলম্ব দাবি',
      'extension_of_time': 'সময় বৃদ্ধির দাবি (EOT)',
      'dispute_adjudication': 'বিরোধ নিষ্পত্তি বোর্ড (DAB)',
      'pipeline_ndt': 'পাইপলাইন এনডিটি (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'রেডিওগ্রাফিক পরীক্ষা ও ওয়েল্ড ছাড়পত্র',
      'weld_integrity': 'ওয়েল্ড অখণ্ডতা ও রেডিওগ্রাফি',
      'ndt_clearance': 'পাইপলাইন এনডিটি ছাড়পত্র',
      'digital_twin': 'ডিজিটাল টুইন ৩ডি (Digital Twin)',
      'digital_twin_subtitle': 'অয়েল ইন্ডিয়া দুলিয়াজান জিআইএস ও ৩ডি লেআউট',
      'gis_site_map': '৩ডি জিআইএস ডিজিটাল টুইন মানচিত্র',
      'chainage_tracking': 'পাইপলাইন চেইনেজ ট্র্যাকিং',
      'executive_reports': 'কার্যনির্বাহী প্রতিবেদন (Executive Reports)',
      'executive_reports_subtitle': 'পিডিএফ ডসিয়ার, স্বাস্থ্য সূচক ও রপ্তানি',
      'health_index': 'প্রকল্প স্বাস্থ্য সূচক',
      'dossier_export': 'কার্যনির্বাহী অগ্রগতি ডসিয়ার',
      'stakeholder_portal': 'অংশীদার পোর্টাল (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'ক্লায়েন্ট, ইপিসি, টিপিআইএ ও ফোরম্যান হাব',
      'contractor_hub': 'ইপিসি ও ঠিকাদার হাব',
      'hold_point_approvals': 'গুণমান হোল্ড পয়েন্ট অনুমোদন',
    },
    'gu': {
      'app_title': 'નિર્માણ ઓએસ',
      'tagline': 'ઔદ્યોગિક પ્રોજેક્ટ મેનેજમેન્ટ અને AI પ્લેટફોર્મ',
      'project_workspace': 'પ્રોજેક્ટ વર્કસ્પેસ',
      'unique_id': 'પ્રોજેક્ટ યુનિક આઈડી',
      'expected_completion': 'અપેક્ષિત પૂર્ણ થવાની તારીખ',
      'original_finish': 'મૂળ કરાર પૂર્ણ થવાની તારીખ',
      'variance': 'સમય મર્યાદામાં વિલંબ',
      'budget_tracking': 'બજેટ અને ખર્ચ ટ્રેકિંગ',
      'total_budget': 'કુલ મંજૂર બજેટ',
      'spent_budget': 'અત્યાર સુધી થયેલ ખર્ચ',
      'remaining_budget': 'બાકી રહેલ ભંડોળ',
      'daily_update': 'દૈનિક પ્રગતિ અને ખર્ચ અપડેટ',
      'schedule_forecast': 'વિલંબ અનુમાન વ્યવસ્થા',
      'hr_workforce': 'એચઆર અને શ્રમિક દળ',
      'labour_attendance': 'ચકાસાયેલ શ્રમિક હાજરી',
      'supervisor_visit': 'સુપરવાઈઝર સાઈટ વિઝિટ ચકાસણી',
      'voice_assistant': 'AI વૉઇસ આસિસ્ટન્ટ',
      'pdf_intelligence': 'ટેન્ડર PDF સારાંશ અને અનુવાદ',
      'gemini_brain': 'જેમિની AI સ્વાયત્ત બ્રેઈન',
      'clock_in': 'GPS હાજરી નોંધણી કરો',
      'mark_presence': 'સાઈટ મુલાકાત નોંધો',
      'review_and_confirm': 'ચકાસો અને પુષ્ટિ કરો',
      'speak_now': 'ગુજરાતી અથવા અંગ્રેજીમાં બોલો...',
      'tender_summary': 'ટેન્ડર મુખ્ય તારણો',
      'convert_to_hindi': 'પેજ માળખું જાળવી રાખતો અનુવાદ',
      'materials_stores': 'સ્ટોર રજિસ્ટર (GRN / GIN)',
      'conflicts_disputes': 'વિવાદ નિવારણ કેન્દ્ર',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC ફેરફારો (FIDIC Variations)',
      'fidic_variations_subtitle': 'કાર્યક્ષેત્ર ફેરફાર અને વેરિએશન રજિસ્ટર',
      'variation_orders': 'ફેરફાર ઓર્ડર અને કાર્યક્ષેત્ર સુધારણા',
      'clause_13_variations': 'FIDIC કલમ 13 ફેરફાર રજિસ્ટર',
      'claims_dab': 'દાવા અને ડીએબી (Claims & DAB)',
      'claims_dab_subtitle': 'વિવાદ નિવારણ અને વિલંબ દાવા',
      'extension_of_time': 'સમય લંબાવવાનો દાવો (EOT)',
      'dispute_adjudication': 'વિવાદ નિવારણ બોર્ડ (DAB)',
      'pipeline_ndt': 'પાઈપલાઈન એનડીટી (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'રેડિયોગ્રાફિક પરીક્ષણ અને વેલ્ડ મંજૂરી',
      'weld_integrity': 'વેલ્ડ અખંડિતતા અને રેડિયોગ્રાફી',
      'ndt_clearance': 'પાઈપલાઈન NDT મંજૂરી',
      'digital_twin': 'ડિજિટલ ટ્વિન 3D (Digital Twin)',
      'digital_twin_subtitle': 'ઓઇલ ઇન્ડિયા દુલિયાજાન GIS અને 3D લેઆઉટ',
      'gis_site_map': '3D જીઆઈએસ ડિજિટલ ટ્વિન નકશો',
      'chainage_tracking': 'પાઈપલાઈન ચેઈનેજ ટ્રેકિંગ',
      'executive_reports': 'કાર્યકારી અહેવાલો (Executive Reports)',
      'executive_reports_subtitle': 'પીડીએફ દસ્તાવેજ, હેલ્થ ઇન્ડેક્સ અને નિકાસ',
      'health_index': 'પ્રોજેક્ટ હેલ્થ ઈન્ડેક્સ',
      'dossier_export': 'કાર્યકારી પ્રગતિ દસ્તાવેજ',
      'stakeholder_portal': 'હિતધારક પોર્ટલ (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'ક્લાયન્ટ, ઈપીસી, ટીપીઆઈએ અને ફોરમેન હબ',
      'contractor_hub': 'ઈપીસી અને કોન્ટ્રાક્ટર હબ',
      'hold_point_approvals': 'ગુણવત્તા હોલ્ડ પોઈન્ટ મંજૂરી',
    },
    'kn': {
      'app_title': 'ನಿರ್ಮಾಣ್ ಓಎಸ್',
      'tagline': 'ಕೈಗಾರಿಕಾ ಯೋಜನೆ ನಿರ್ವಹಣೆ ಮತ್ತು AI ವೇದಿಕೆ',
      'project_workspace': 'ಯೋಜನಾ ಕಾರ್ಯಕ್ಷೇತ್ರ',
      'unique_id': 'ಯೋಜನೆಯ ವಿಶಿಷ್ಟ ಐಡಿ',
      'expected_completion': 'ಅಂದಾಜು ಮುಕ್ತಾಯ ದಿನಾಂಕ',
      'original_finish': 'ಮೂಲ ಒಪ್ಪಂದದ ಮುಕ್ತಾಯ ದಿನಾಂಕ',
      'variance': 'ಸಮಯ ವಿಳಂಬ ವ್ಯತ್ಯಾಸ',
      'budget_tracking': 'ಬಜೆಟ್ ಮತ್ತು ವೆಚ್ಚ ಟ್ರ್ಯಾಕಿಂಗ್',
      'total_budget': 'ಒಟ್ಟು ಮಂಜೂರಾದ ಬಜೆಟ್',
      'spent_budget': 'ಇಲ್ಲಿಯವರೆಗೆ ವೆಚ್ಚವಾದ ಮೊತ್ತ',
      'remaining_budget': 'ಉಳಿದ ಬಜೆಟ್',
      'daily_update': 'ದೈನಂದಿನ ಪ್ರಗತಿ ಮತ್ತು ವೆಚ್ಚ ಅಪ್‌ಡೇಟ್',
      'schedule_forecast': 'ವಿಳಂಬ ಮುನ್ಸೂಚನೆ ಎಂಜಿನ್',
      'hr_workforce': 'ಮಾನವ ಸಂಪನ್ಮೂಲ ಮತ್ತು ಕಾರ್ಮಿಕರು',
      'labour_attendance': 'ದೃಢೀಕರಿಸಿದ ಕಾರ್ಮಿಕರ ಹಾಜರಾತಿ',
      'supervisor_visit': 'ಸೈಟ್ ಮೇಲ್ವಿಚಾರಕರ ಉಪಸ್ಥಿತಿ ದೃಢೀಕರಣ',
      'voice_assistant': 'AI ಧ್ವನಿ ಸಹಾಯಕ',
      'pdf_intelligence': 'ಟೆಂಡರ್ PDF ಸಾರಾಂಶ ಮತ್ತು ಅನುವಾದ',
      'gemini_brain': 'ಜೆಮಿನಿ AI ಮೆದುಳು',
      'clock_in': 'GPS ಹಾಜರಾತಿ ದೃಢೀಕರಿಸಿ',
      'mark_presence': 'ಸೈಟ್ ಭೇಟಿ ದಾಖಲಿಸಿ',
      'review_and_confirm': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ದೃಢೀಕರಿಸಿ',
      'speak_now': 'ಕನ್ನಡ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಮಾತನಾಡಿ...',
      'tender_summary': 'ಟೆಂಡರ್ ಮುಖ್ಯ ಅಂಶಗಳ ಸಾರಾಂಶ',
      'convert_to_hindi': 'ಪುಟ ರಚನೆ ಬದಲಾಗದ ಅನುವಾದ',
      'materials_stores': 'ದಾಸ್ತಾನು ನೋಂದಣಿ (GRN / GIN)',
      'conflicts_disputes': 'ವಿವಾದ ಪರಿಹಾರ ಕೇಂದ್ರ',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC ಬದಲಾವಣೆಗಳು (FIDIC Variations)',
      'fidic_variations_subtitle': 'ವ್ಯಾಪ್ತಿ ಬದಲಾವಣೆ ಮತ್ತು ವ್ಯತ್ಯಾಸ ನೋಂದಣಿ',
      'variation_orders': 'ಬದಲಾವಣೆ ಆದೇಶಗಳು ಮತ್ತು ವ್ಯಾಪ್ತಿ ಬದಲಾವಣೆ',
      'clause_13_variations': 'FIDIC ಷರತ್ತು 13 ಬದಲಾವಣೆ ನೋಂದಣಿ',
      'claims_dab': 'ಕ್ಲೈಮ್‌ಗಳು ಮತ್ತು DAB (Claims & DAB)',
      'claims_dab_subtitle': 'ವಿವಾದ ತೀರ್ಪು ಮತ್ತು ವಿಳಂಬ ಕ್ಲೈಮ್‌ಗಳು',
      'extension_of_time': 'ಸಮಯ ವಿಸ್ತರಣೆ ಕ್ಲೈಮ್ (EOT)',
      'dispute_adjudication': 'ವಿವಾದ ತೀರ್ಪು ಮಂಡಳಿ (DAB)',
      'pipeline_ndt': 'ಪೈಪ್‌ಲೈನ್ NDT (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'ರೇಡಿಯೋಗ್ರಾಫಿಕ್ ಪರೀಕ್ಷೆ ಮತ್ತು ವೆಲ್ಡ್ ಅನುಮತಿ',
      'weld_integrity': 'ವೆಲ್ಡ್ ಸಮಗ್ರತೆ ಮತ್ತು ರೇಡಿಯೋಗ್ರಫಿ',
      'ndt_clearance': 'ಪೈಪ್‌ಲೈನ್ NDT ಅನುಮತಿ',
      'digital_twin': 'ಡಿಜಿಟಲ್ ಟ್ವಿನ್ 3D (Digital Twin)',
      'digital_twin_subtitle': 'ಆಯಿಲ್ ಇಂಡಿಯಾ ದುಲಿಯಾಜಾನ್ GIS & 3D ವಿನ್ಯಾಸ',
      'gis_site_map': '3D GIS ಡಿಜಿಟಲ್ ಟ್ವಿನ್ ನಕ್ಷೆ',
      'chainage_tracking': 'ಪೈಪ್‌ಲೈನ್ ಚೈನೇಜ್ ಟ್ರ್ಯಾಕಿಂಗ್',
      'executive_reports': 'ಕಾರ್ಯನಿರ್ವಾಹಕ ವರದಿಗಳು (Executive Reports)',
      'executive_reports_subtitle': 'PDF ಕಡತ, ಆರೋಗ್ಯ ಸೂಚ್ಯಂಕ ಮತ್ತು ರಫ್ತು',
      'health_index': 'ಯೋಜನಾ ಆರೋಗ್ಯ ಸೂಚ್ಯಂಕ',
      'dossier_export': 'ಕಾರ್ಯನಿರ್ವಾಹಕ ಪ್ರಗತಿ ಕಡತ',
      'stakeholder_portal': 'ಪಾಲುದಾರರ ಪೋರ್ಟಲ್ (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'ಕ್ಲೈಂಟ್, EPC, TPIA ಮತ್ತು ಫೋರ್‌ಮನ್ ಹಬ್',
      'contractor_hub': 'ಇಪಿಸಿ ಮತ್ತು ಗುತ್ತಿಗೆದಾರರ ಕೇಂದ್ರ',
      'hold_point_approvals': 'ಗುಣಮಟ್ಟ ಹೋಲ್ಡ್ ಪಾಯಿಂಟ್ ಅನುಮೋದನೆಗಳು',
    },
    'ml': {
      'app_title': 'നിർമ്മാൺ ഒഎസ്',
      'tagline': 'വ്യാവസായിക പ്രോജക്ട് മാനേജ്മെന്റും എഐ പ്ലാറ്റ്‌ഫോമും',
      'project_workspace': 'പ്രോജക്റ്റ് വർക്ക്‌സ്‌പേസ്',
      'unique_id': 'പ്രോജക്റ്റ് തനത് ഐഡി',
      'expected_completion': 'പ്രതീക്ഷിക്കുന്ന പൂർത്തീകരണ തീയതി',
      'original_finish': 'യഥാർത്ഥ കരാർ കാലാവധി',
      'variance': 'സമയ കാലതാമസം',
      'budget_tracking': 'ബജറ്റും ചെലവ് ട്രാക്കിംഗും',
      'total_budget': 'ആകെ അനുവദിച്ച ബജറ്റ്',
      'spent_budget': 'ഇതുവരെ ചെലവഴിച്ച തുക',
      'remaining_budget': 'ബാക്കിയുള്ള തുക',
      'daily_update': 'ദിവസേനയുള്ള വിവരങ്ങൾ',
      'schedule_forecast': 'കാലതാമസ പ്രവചന സംവിധാനം',
      'hr_workforce': 'എച്ച്ആറും ജീവനക്കാരും',
      'labour_attendance': 'തൊഴിലാളി ഹാജർ നില',
      'supervisor_visit': 'മേൽനോട്ടക്കാരന്റെ സന്ദർശനം സ്ഥിരീകരിക്കൽ',
      'voice_assistant': 'എഐ വോയ്‌സ് അസിസ്റ്റന്റ്',
      'pdf_intelligence': 'ടെൻഡർ പിഡിഎഫ് സംഗ്രഹം',
      'gemini_brain': 'ജെമിനി എഐ ബ്രെയിൻ',
      'clock_in': 'ജിപിഎസ് ഹാജർ രേഖപ്പെടുത്തുക',
      'mark_presence': 'സന്ദർശനം രേഖപ്പെടുത്തുക',
      'review_and_confirm': 'സ്ഥിരീകരിക്കുക',
      'speak_now': 'മലയാളത്തിലോ ഇംഗ്ലീഷിലോ സംസാരിക്കുക...',
      'tender_summary': 'പ്രധാന വിവരങ്ങൾ',
      'convert_to_hindi': 'പേജ് ഘടന നഷ്ടപ്പെടാത്ത വിവർത്തനം',
      'materials_stores': 'സ്റ്റോർ ലെഡ്ജർ (GRN / GIN)',
      'conflicts_disputes': 'തർക്ക പരിഹാര കേന്ദ്രം',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      'fidic_variations': 'FIDIC വ്യതിയാനങ്ങൾ (FIDIC Variations)',
      'fidic_variations_subtitle': 'പരിധി മാറ്റവും വ്യതിയാന രജിസ്റ്ററും',
      'variation_orders': 'വ്യതിയാന ഉത്തരവുകളും പരിധി മാറ്റങ്ങളും',
      'clause_13_variations': 'FIDIC ക്ലോസ് 13 വ്യതിയാന രജിസ്റ്റർ',
      'claims_dab': 'അവകാശവാദങ്ങളും DAB-യും (Claims & DAB)',
      'claims_dab_subtitle': 'തർക്ക പരിഹാരവും കാലതാമസ അവകാശവാദങ്ങളും',
      'extension_of_time': 'സമയപരിധി നീട്ടൽ ക്ലെയിം (EOT)',
      'dispute_adjudication': 'തർക്ക പരിഹാര ബോർഡ് (DAB)',
      'pipeline_ndt': 'പൈപ്പ്‌ലൈൻ NDT (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'റേഡിയോഗ്രാഫിക് പരിശോധനയും വെൽഡ് ക്ലിയറൻസും',
      'weld_integrity': 'വെൽഡ് സമഗ്രതയും റേഡിയോഗ്രഫിയും',
      'ndt_clearance': 'പൈപ്പ്‌ലൈൻ NDT ക്ലിയറൻസ്',
      'digital_twin': 'ഡിജിറ്റൽ ട്വിൻ 3D (Digital Twin)',
      'digital_twin_subtitle': 'ഓയിൽ ഇന്ത്യ ദുലിയാജാൻ GIS & 3D ലേഔട്ട്',
      'gis_site_map': '3D ജിഐഎസ് ഡിജിറ്റൽ ട്വിൻ മാപ്പ്',
      'chainage_tracking': 'പൈപ്പ്‌ലൈൻ ചെയിനേജ് ട്രാക്കിംഗ്',
      'executive_reports': 'എക്സിക്യൂട്ടീവ് റിപ്പോർട്ടുകൾ (Executive Reports)',
      'executive_reports_subtitle': 'PDF രേഖ, ആരോഗ്യ സൂചിക, കയറ്റുമതി',
      'health_index': 'പ്രോജക്ട് ആരോഗ്യ സൂചിക',
      'dossier_export': 'എക്സിക്യൂട്ടീവ് പുരോഗതി രേഖകൾ',
      'stakeholder_portal': 'പങ്കാളിത്ത പോർട്ടൽ (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'ക്ലയന്റ്, EPC, TPIA, ഫോർമാൻ ഹബ്',
      'contractor_hub': 'ഇപിസിയും കരാറുകാരുടെ ഹബ്ബും',
      'hold_point_approvals': 'ഗുണനിലവാര ഹോൾഡ് പോയിന്റ് അനുമതികൾ',
    },
    'as': {
      'app_title': 'নিৰ্মাণ ওএছ',
      'tagline': 'ঔদ্যোগিক প্ৰকল্প পৰিচালনা আৰু এআই প্লেটফৰ্ম',
      'project_workspace': 'প্ৰকল্প কাৰ্যক্ষেত্ৰ',
      'unique_id': 'প্ৰকল্পৰ অনন্য আই-ডি',
      'expected_completion': 'সমাপ্তিৰ আনুমানিক তাৰিখ',
      'original_finish': 'মূল চুক্তি সমাপ্তিৰ তাৰিখ',
      'variance': 'সময়ৰ বিলম্ব পাৰ্থক্য',
      'budget_tracking': 'বাজেট আৰু ব্যয় অনুসৰণ',
      'total_budget': 'মুঠ অনুমোদিত বাজেট',
      'spent_budget': 'বৰ্তমানলৈকে হোৱা খৰচ',
      'remaining_budget': 'বাকী থকা পুঁজি',
      'daily_update': 'দৈনিক অগ্ৰগতি আৰু ব্যয় আপডে’ট',
      'schedule_forecast': 'বিলম্ব পূৰ্বানুমান ব্যৱস্থা',
      'hr_workforce': 'মানৱ সম্পদ আৰু শ্ৰমিক দল',
      'labour_attendance': 'প্ৰমাণীকৃত শ্ৰমিক উপস্থিতি',
      'supervisor_visit': 'ছুপাৰভাইজৰৰ উপস্থিতি পৰীক্ষণ',
      'voice_assistant': 'এআই ভইচ সহায়ক',
      'pdf_intelligence': 'টেণ্ডাৰ পিডিএফ সাৰাংশ আৰু অনুবাদ',
      'gemini_brain': 'জেমিনি এআই মগজু',
      'clock_in': 'GPS উপস্থিতি নিশ্চিত কৰক',
      'mark_presence': 'ছাইট ভ্ৰমণ নথীভুক্ত কৰক',
      'review_and_confirm': 'পৰীক্ষা আৰু নিশ্চিত কৰক',
      'speak_now': 'অসমীয়া বা ইংৰাজীত কওক...',
      'tender_summary': 'টেণ্ডাৰ মূল সাৰাংশ',
      'convert_to_hindi': 'পৃষ্ঠা বিন্যাস অটুট থকা অনুবাদ',
      'materials_stores': 'ষ্ট’ৰ খতিয়ান (GRN / GIN)',
      'conflicts_disputes': 'বিবাদ নিষ্পত্তি কেন্দ্ৰ',
      // Newly added sections: FIDIC Variations, Claims & DAB, Pipeline NDT, Digital Twin, Executive Reports, Stakeholder Portal
      // Special focus on Assamese (অসমীয়া) for Upper Assam (Duliajan) Oil India pipeline operations
      'fidic_variations': 'এফআইডিআইচি পৰিৱৰ্তন (FIDIC Variations)',
      'fidic_variations_subtitle': 'কাৰ্যপৰিসৰ সালসলনি আৰু পৰিৱৰ্তন পঞ্জী',
      'variation_orders': 'পৰিৱৰ্তন আদেশ আৰু পৰিসৰ সালসলনি',
      'clause_13_variations': 'এফআইডিআইচি ক্লজ ১৩ পৰিৱৰ্তন পঞ্জী',
      'claims_dab': 'দাবী আৰু ডি.এ.বি. (Claims & DAB)',
      'claims_dab_subtitle': 'বিবাদ নিষ্পত্তি আৰু বিলম্ব দাবী',
      'extension_of_time': 'সময় বৃদ্ধিৰ দাবী (EOT)',
      'dispute_adjudication': 'বিবাদ নিষ্পত্তি ব’ৰ্ড (DAB)',
      'pipeline_ndt': 'পাইপলাইন এন.ডি.টি. (Pipeline NDT)',
      'pipeline_ndt_subtitle': 'ৰেডিঅ’গ্ৰাফিক পৰীক্ষা আৰু ৱেল্ড ক্লিয়াৰেন্স',
      'weld_integrity': 'ৱেল্ড অখণ্ডতা আৰু ৰেডিঅ’গ্ৰাফী',
      'ndt_clearance': 'পাইপলাইন এনডিটি অনুমোদন',
      'digital_twin': 'ডিজিটেল টুইন ৩ডি (Digital Twin)',
      'digital_twin_subtitle': 'অইল ইণ্ডিয়া দুলীয়াজান জিআইএছ আৰু ৩ডি লেআউট',
      'gis_site_map': '৩ডি জিআইএছ ডিজিটেল টুইন মানচিত্ৰ',
      'chainage_tracking': 'পাইপলাইন চেইনেজ অনুসৰণ',
      'executive_reports': 'কাৰ্যবাহী প্ৰতিবেদন (Executive Reports)',
      'executive_reports_subtitle': 'পিডিএফ ডছিয়াৰ, স্বাস্থ্য সূচক আৰু ৰপ্তানি',
      'health_index': 'প্ৰকল্প স্বাস্থ্য সূচক',
      'dossier_export': 'কাৰ্যবাহী অগ্ৰগতি নথিপত্ৰ ৰপ্তানি',
      'stakeholder_portal': 'অংশীদাৰ পৰ্টেল (Stakeholder Portal)',
      'stakeholder_portal_subtitle': 'ক্লায়েণ্ট, ইপিচি, টিপিআইএ আৰু ফৰমেন হাব',
      'contractor_hub': 'ইপিচি আৰু ঠিকাদাৰ কেন্দ্ৰ',
      'hold_point_approvals': 'গুণমান নিশ্চিতকৰণ অনুমোদন (Hold Points)',
    },
    'pa': {
      'app_title': 'ਨਿਰਮਾਣ ਓਐਸ',
      'tagline': 'ਉਦਯੋਗਿਕ ਪ੍ਰੋਜੈਕਟ ਪ੍ਰਬੰਧਨ ਅਤੇ ਏਆਈ ਪਲੇਟਫਾਰਮ',
      'project_workspace': 'ਪ੍ਰੋਜੈਕਟ ਵਰਕਸਪੇਸ',
      'unique_id': 'ਪ੍ਰੋਜੈਕਟ ਵਿਲੱਖਣ ਆਈਡੀ',
      'expected_completion': 'ਸੰਭਾਵਿਤ ਮੁਕੰਮਲ ਹੋਣ ਦੀ ਮਿਤੀ',
      'original_finish': 'ਅਸਲ ਇਕਰਾਰਨਾਮਾ ਸਮਾਪਤੀ ਮਿਤੀ',
      'variance': 'ਸਮਾਂ ਸਾਰਣੀ ਵਿੱਚ ਦੇਰੀ',
      'budget_tracking': 'ਬਜਟ ਅਤੇ ਖਰਚ ਟਰੈਕਿੰਗ',
      'total_budget': 'ਕੁੱਲ ਮਨਜ਼ੂਰ ਬਜਟ',
      'spent_budget': 'ਖਰਚੀ ਗਈ ਰਕਮ',
      'remaining_budget': 'ਬਾਕੀ ਬਚਿਆ ਬਜਟ',
      'daily_update': 'ਰੋਜ਼ਾਨਾ ਪ੍ਰਗਤੀ ਅੱਪਡੇਟ',
      'schedule_forecast': 'ਸ਼ਡਿਊਲ ਭਵਿੱਖਬਾਣੀ ਇੰਜਣ',
      'hr_workforce': 'ਕਰਮਚਾਰੀ ਅਤੇ ਮਜ਼ਦੂਰ ਪ੍ਰਬੰਧਨ',
      'labour_attendance': 'ਪ੍ਰਮਾਣਿਤ ਮਜ਼ਦੂਰ ਹਾਜ਼ਰੀ',
      'supervisor_visit': 'ਸਾਈਟ ਨਿਰੀਖਣ ਪ੍ਰਮਾਣਿਕਤਾ',
      'voice_assistant': 'ਏਆਈ ਵੌਇਸ ਅਸਿਸਟੈਂਟ',
      'pdf_intelligence': 'ਟੈਂਡਰ ਪੀਡੀਐਫ ਸਾਰ ਅਤੇ ਅਨੁਵਾਦ',
      'gemini_brain': 'ਜੈਮਿਨੀ ਏਆਈ ਬ੍ਰੇਨ',
      'clock_in': 'ਜੀਪੀਐਸ ਜੀਓਫੈਂਸ ਹਾਜ਼ਰੀ',
      'mark_presence': 'ਸਾਈਟ ਵਿਜ਼ਿਟ ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
      'materials_stores': 'ਸਟੋਰ ਲੇਜ਼ਰ (GRN / GIN)',
      'conflicts_disputes': 'ਵਿਵਾਦ ਅਤੇ ਜੋਖਮ ਕੇਂਦਰ',
    },
    'or': {
      'app_title': 'ନିର୍ମାଣ ଓଏସ',
      'tagline': 'ଶିଳ୍ପ ପ୍ରକଳ୍ପ ପରିଚାଳନା ଓ ଏଆଇ ପ୍ଲାଟଫର୍ମ',
      'project_workspace': 'ପ୍ରକଳ୍ପ କାର୍ଯ୍ୟକ୍ଷେତ୍ର',
      'unique_id': 'ପ୍ରକଳ୍ପ ଆଇଡି',
      'expected_completion': 'ସମାପ୍ତି ଆଶା କରାଯାଉଥିବା ତାରିଖ',
      'original_finish': 'ମୂଳ ଚୁକ୍ତି ସମାପ୍ତି ତାରିଖ',
      'variance': 'ସମୟସୀମା ବିଳମ୍ବ',
      'budget_tracking': 'ବଜେଟ ଓ ଖର୍ଚ୍ଚ ଟ୍ରାକିଂ',
      'total_budget': 'ମୋଟ ମଞ୍ଜୁର ବଜେଟ',
      'spent_budget': 'ଖର୍ଚ୍ଚ ହୋଇଥିବା ରାଶି',
      'remaining_budget': 'ଅବଶିଷ୍ଟ ବଜେଟ',
      'daily_update': 'ଦୈନିକ ପ୍ରଗତି ଅପଡେଟ',
      'schedule_forecast': 'କାର୍ଯ୍ୟସୂଚୀ ପୂର୍ବାନୁମାନ',
      'hr_workforce': 'କର୍ମଚାରୀ ଓ ଶ୍ରମିକ',
      'labour_attendance': 'ଶ୍ରମିକ ଉପସ୍ଥିତି',
      'supervisor_visit': 'ସାଇଟ ପରିଦର୍ଶନ ପ୍ରମାଣ',
      'voice_assistant': 'ଏଆଇ ଭଏସ ସହାୟକ',
      'pdf_intelligence': 'ଟେଣ୍ଡର ପିଡିଏଫ ବିଶ୍ଳେଷଣ',
      'gemini_brain': 'ଜେମିନି ଏଆଇ ବ୍ରେନ',
      'clock_in': 'ଜିପିଏସ ଉପସ୍ଥିତି',
      'mark_presence': 'ପରିଦର୍ଶନ ନିଶ୍ଚିତ କରନ୍ତୁ',
      'materials_stores': 'ଷ୍ଟୋର ଖାତା (GRN / GIN)',
      'conflicts_disputes': 'ବିବାଦ ପରିଚାଳନା କେନ୍ଦ୍ର',
    },
    'ur': {
      'app_title': 'نرمان او ایس',
      'tagline': 'صنعتی پروجیکٹ مینجمنٹ اور مصنوعی ذہانت پلیٹ فارم',
      'project_workspace': 'پروجیکٹ ورک اسپیس',
      'unique_id': 'پروجیکٹ منفرد شناختی کوڈ',
      'expected_completion': 'تکمیل کی متوقع تاریخ',
      'original_finish': 'معاہدے کی اصل اختتامی تاریخ',
      'variance': 'تاخیر کا تخمینہ',
      'budget_tracking': 'بجٹ اور اخراجات کا سراغ',
      'total_budget': 'کل منظور شدہ بجٹ',
      'spent_budget': 'خرچ شدہ رقم',
      'remaining_budget': 'باقی ماندہ رقم',
      'daily_update': 'روزانہ پیش رفت اپ ڈیٹ',
      'schedule_forecast': 'پیشن گوئی انجن',
      'hr_workforce': 'ملازمین اور افرادی قوت',
      'labour_attendance': 'مصدقہ مزدور حاضری',
      'supervisor_visit': 'سائٹ معائنے کا ثبوت',
      'voice_assistant': 'آواز پر مبنی معاون',
      'pdf_intelligence': 'ٹینڈر پی ڈی ایف تجزیہ اور ترجمہ',
      'gemini_brain': 'جیمنی اے آئی برین',
      'clock_in': 'جی پی ایس حاضری درج کریں',
      'mark_presence': 'معائنے کی تصدیق کریں',
      'materials_stores': 'اسٹور لیجر (GRN / GIN)',
      'conflicts_disputes': 'تنازعات و خطرات کا مرکز',
    },
    'mai': {
      'app_title': 'निर्माण ओएस',
      'tagline': 'औद्योगिक परियोजना प्रबंधन एवं एआई इंटेलिजेंस',
      'project_workspace': 'प्रोजेक्ट वर्कस्पेस',
      'unique_id': 'प्रोजेक्ट विशिष्ट पहचान',
      'expected_completion': 'अनुमानित पूर्णता तिथि',
      'original_finish': 'मूल अनुबंध समाप्ति तिथि',
      'variance': 'समय में विलंब',
      'budget_tracking': 'बजट एवं व्यय ट्रैकिंग',
      'total_budget': 'कुल स्वीकृत बजट',
      'spent_budget': 'खर्च भेल राशि',
      'remaining_budget': 'बचायल बजट',
      'daily_update': 'दैनिक प्रगति रिपोर्ट',
      'schedule_forecast': 'अनुसूची पूर्वानुमान',
      'hr_workforce': 'श्रमिक एवं कार्यबल',
      'labour_attendance': 'प्रमाणित श्रमिक उपस्थिति',
      'supervisor_visit': 'स्थल निरीक्षण प्रमाण',
      'voice_assistant': 'एआई आवाज सहायक',
      'pdf_intelligence': 'निविदा पीडीएफ सारांश',
      'gemini_brain': 'जेमिनी एआई ब्रेन',
      'clock_in': 'जीपीएस हाजिरी दर्ज करू',
      'mark_presence': 'निरीक्षण प्रमाणित करू',
      'materials_stores': 'स्टोर बहीखाता (GRN / GIN)',
      'conflicts_disputes': 'विवाद एवं जोखिम केंद्र',
    },
    'sa': {
      'app_title': 'निर्माण ओएस्',
      'tagline': 'औद्योगिकयोजनाप्रबन्धनम् कृत्रिमबुद्धिप्रणाली च',
      'project_workspace': 'योजनाकार्यक्षेत्रम्',
      'unique_id': 'योजनाविशिष्टपरिचयः',
      'expected_completion': 'अनुमानितसमाप्तिदिनाङ्कः',
      'original_finish': 'मूलअनुबन्धसमाप्तिदिनाङ्कः',
      'variance': 'कालविलम्बः',
      'budget_tracking': 'व्ययमाननिरीक्षणम्',
      'total_budget': 'कुलस्वीकृतव्ययः',
      'spent_budget': 'व्ययीकृतधनम्',
      'remaining_budget': 'अवशिष्टधनम्',
      'daily_update': 'दैनिकप्रगतिविवरणम्',
      'schedule_forecast': 'कालसूचिकापूर्वानुमानम्',
      'hr_workforce': 'कर्मचारिणः श्रमिकाः च',
      'labour_attendance': 'प्रमाणीकृतश्रमिकोपस्थितिः',
      'supervisor_visit': 'क्षेत्रनिरीक्षणप्रमाणम्',
      'voice_assistant': 'वाक्सहायकः',
      'pdf_intelligence': 'निविदापत्रसारांशः',
      'gemini_brain': 'जेमिनी मस्तिष्कमंत्रणा',
      'clock_in': 'स्थानप्रमाणीकरणोपस्थितिः',
      'mark_presence': 'उपस्थितिं प्रमाणीकुरु',
      'materials_stores': 'वस्तुसंग्रहालयलेखा (GRN / GIN)',
      'conflicts_disputes': 'विवादप्रबन्धनकेन्द्रम्',
    },
  };

  static AppLanguage getLanguage(String code) {
    return supportedLanguages.firstWhere(
      (lang) => lang.code == code,
      orElse: () => supportedLanguages.first,
    );
  }

  static bool isSupported(String code) {
    return supportedLanguages.any((lang) => lang.code == code);
  }

  static List<String> get supportedLanguageCodes {
    return supportedLanguages.map((l) => l.code).toList();
  }

  static String text(String key, [String? languageCode]) {
    final code = languageCode ?? LanguageController.instance.currentLanguageCode;
    final langMap = _localizedValues[code] ?? _localizedValues['en']!;
    return langMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}
